import type { CredentialAuthorization } from "./http.js";
import type { TrackerCredentialBroker } from "./tracker-credentials.js";
function json(status:number,body:Record<string,unknown>,origin?:string){return Response.json(body,{status,headers:{"cache-control":"no-store","x-content-type-options":"nosniff",...(origin?{"access-control-allow-origin":origin,vary:"origin"}:{})}})}
export async function handleTrackerCredentialSave(request:Request,input:{allowedOrigin:string;authorize:CredentialAuthorization;broker:Pick<TrackerCredentialBroker,"save">}){
 const origin=request.headers.get("origin");if(origin!==input.allowedOrigin)return json(403,{error:"origin_not_allowed"});if(request.method==="OPTIONS")return new Response(null,{status:204,headers:{"access-control-allow-origin":origin,"access-control-allow-methods":"POST, OPTIONS","access-control-allow-headers":"authorization, content-type",vary:"origin"}});if(request.method!=="POST")return json(405,{error:"method_not_allowed"},origin);
 const authorization=request.headers.get("authorization")??"";if(!authorization.startsWith("Bearer "))return json(401,{error:"authentication_required"},origin);let body:Record<string,unknown>;try{const raw=await request.text();if(Buffer.byteLength(raw)>16_384)return json(413,{error:"request_too_large"},origin);body=JSON.parse(raw)}catch{return json(400,{error:"invalid_request"},origin)}
 if(typeof body.organizationId!=="string"||(body.repositoryId!==undefined&&typeof body.repositoryId!=="string")||!["linear","jira"].includes(String(body.provider))||typeof body.workspaceId!=="string"||typeof body.token!=="string"||body.token.length<8||!Array.isArray(body.scopes)||body.scopes.some(value=>typeof value!=="string")||body.workspaceId.length>300)return json(400,{error:"invalid_request"},origin);
 try{const repositoryId=body.repositoryId as string|undefined,{actorId}=await input.authorize({token:authorization.slice(7),organizationId:body.organizationId,...(repositoryId?{repositoryId}:{})}),saved=await input.broker.save({actorId,organizationId:body.organizationId,...(repositoryId?{repositoryId}:{}),provider:body.provider as"linear"|"jira",workspaceId:body.workspaceId,token:body.token,scopes:body.scopes as string[],...(typeof body.expiresAt==="number"?{expiresAt:body.expiresAt}:{}),...(typeof body.replacesConnectionId==="string"?{replacesConnectionId:body.replacesConnectionId}:{})});return json(201,{connection:saved},origin)}catch(error){const code=error instanceof Error?error.message:"tracker_save_failed",safe=["invalid_key","rate_limited","recent_reauthentication_required","not_found_or_forbidden"].includes(code)?code:"tracker_save_failed";return json(safe==="invalid_key"?422:safe==="rate_limited"?429:safe==="recent_reauthentication_required"?401:safe==="not_found_or_forbidden"?404:503,{error:safe},origin)}
}
