import { query } from "./_generated/server";
import { rowCostUsd } from "./lib/usageCost";

// BuildIT has no analytics, and every number it published about itself was a literal typed into a
// page - the exact rot track-record.mjs was written to stop, except that file is regenerated by
// hand and is a snapshot by the time anyone reads it. So a stranger evaluating BuildIT had to take
// the operating numbers on trust, which is the one thing this product exists to refuse.
//
// This is the live version: one unauthenticated query, aggregate counts only, read from the same
// production database the product runs on. It is declared "public_webhook" in
// publicFunctionPolicy.ts - the only authorization value that means "no identity required" - and
// its response is "metadata" because nothing it returns is derived from a customer's source.
//
// What it must never return, and the reason each one is missing rather than merely unused:
//   - repository owner/name, and the repositoryId itself: naming who BuildIT reviews for is a
//     customer disclosure, so only the count of distinct ids leaves this function.
//   - organizationId, organization name or slug, membership counts: same, one level up.
//   - triggerActor, cancelledBy, createdBy, or any other actor field: those are GitHub logins.
//   - finding text, path, ruleId, fingerprintHmac, severity per repository: findings are
//     source-derived, and a fingerprint is a stable identifier of one line of someone's code.
//   - headSha/baseSha/branch hashes: an sha is a join key back to a public repository.
//   - the ledger's currency label and per-organization spend: only one total in USD.
// Every value below is either a count, a duration, a sum, or a status literal from
// validators.ts - BuildIT's own enum, not customer data.

// Bounded for the same reason activation.ts is: this feeds a live subscription that re-executes on
// every matching write, and an unbounded read of an append-only table eventually crosses Convex's
// per-query read limit, where the query hard-fails rather than degrading. Newest-first, so a
// truncated answer is the recent window rather than an arbitrary slice - and `truncated` says so
// instead of letting a capped count read as a total.
const rowCeiling = 2_000;


export const summary = query({
  args: {},
  handler: async (ctx) => {
    const [reviews, findings, ledger] = await Promise.all([
      ctx.db.query("reviews").order("desc").take(rowCeiling),
      ctx.db.query("findings").order("desc").take(rowCeiling),
      ctx.db.query("usageLedger").withIndex("by_time").order("desc").take(rowCeiling),
    ]);

    // Present statuses only. Zero-filling the whole enum would put eighteen rows on the page,
    // most of them stating that something never happened.
    const byStatus: Record<string, number> = {};
    for (const review of reviews) byStatus[review.status] = (byStatus[review.status] ?? 0) + 1;

    // The id is used to size a set and is then discarded; it is never returned.
    const repositoriesReviewed = new Set(reviews.map(review => String(review.repositoryId))).size;

    // No duration statistic. It was on this page and it was wrong: verdict-reaching reviews showed
    // a median of 0.1s while platform failures showed 87s, because a review row's createdAt and
    // startedAt are both re-stamped per execution generation, so neither pair measures the wait a
    // person experienced. A latency number nobody can defend does not belong on a page whose whole
    // claim is that the numbers are checkable - so it is absent, and the absence is deliberate.

    // kind "model_tokens" is the only priced kind; sandbox_seconds is recorded at unitCost 0. The
    // ledger's currency label is "provider_billed" because the spend lands on the customer's own
    // provider key, not on BuildIT - so this is what BuildIT's reviews have cost to run, and the
    // page has to say that rather than implying revenue.
    const modelRows = ledger.filter(row => row.kind === "model_tokens");
    const modelSpendUsd = modelRows.reduce((sum, row) => sum + rowCostUsd(row), 0);
    const modelTokens = modelRows.reduce((sum, row) => sum + row.quantity, 0);

    return {
      generatedAt: Date.now(),
      rowCeiling,
      reviews: {
        counted: reviews.length,
        truncated: reviews.length === rowCeiling,
        byStatus,
        repositoriesReviewed,
      },
      findings: {
        counted: findings.length,
        truncated: findings.length === rowCeiling,
      },
      spend: {
        modelSpendUsd,
        modelTokens,
        counted: ledger.length,
        truncated: ledger.length === rowCeiling,
      },
    };
  },
});
