import { query } from "./_generated/server";
import { rowCostUsd } from "./lib/usageCost";

// BuildIT has no analytics, and every number it published about itself was a literal typed into a
// page - the exact rot track-record.mjs was written to stop, except that file is regenerated by
// hand and is a snapshot by the time anyone reads it. So a stranger evaluating BuildIT had to take
// the operating numbers on trust, which is the one thing this product exists to refuse.
//
// This is the live version: one unauthenticated query, aggregate counts only, read from the same
// production database the product runs on. It is declared "public_webhook" in
// publicFunctionPolicy.ts - the only authorization value that means "no identity required" - and
// its response is "metadata" because nothing it returns is derived from a customer's source.
//
// What it must never return, and the reason each one is missing rather than merely unused:
//   - repository owner/name, and the repositoryId itself: naming who BuildIT reviews for is a
//     customer disclosure, so only the count of distinct ids leaves this function.
//   - organizationId, organization name or slug, membership counts: same, one level up.
//   - triggerActor, cancelledBy, createdBy, or any other actor field: those are GitHub logins.
//   - finding text, path, ruleId, fingerprintHmac, severity per repository: findings are
//     source-derived, and a fingerprint is a stable identifier of one line of someone's code.
//   - headSha/baseSha/branch hashes: an sha is a join key back to a public repository.
//   - the ledger's currency label and per-organization spend: only one total in USD.
// Every value below is either a count, a duration, a sum, or a status literal from
// validators.ts - BuildIT's own enum, not customer data.

// Bounded for the same reason activation.ts is: this feeds a live subscription that re-executes on
// every matching write, and an unbounded read of an append-only table eventually crosses Convex's
// per-query read limit, where the query hard-fails rather than degrading. Newest-first, so a
// truncated answer is the recent window rather than an arbitrary slice - and `truncated` says so
// instead of letting a capped count read as a total.
const rowCeiling = 2_000;

function percentile(sortedAscending: number[], fraction: number) {
  if (sortedAscending.length === 0) return null;
  const rank = Math.min(sortedAscending.length - 1, Math.max(0, Math.ceil(fraction * sortedAscending.length) - 1));
  return sortedAscending[rank]!;
}

export const summary = query({
  args: {},
  handler: async (ctx) => {
    const [reviews, findings, ledger] = await Promise.all([
      ctx.db.query("reviews").order("desc").take(rowCeiling),
      ctx.db.query("findings").order("desc").take(rowCeiling),
      ctx.db.query("usageLedger").withIndex("by_time").order("desc").take(rowCeiling),
    ]);

    // Present statuses only. Zero-filling the whole enum would put eighteen rows on the page,
    // most of them stating that something never happened.
    const byStatus: Record<string, number> = {};
    for (const review of reviews) byStatus[review.status] = (byStatus[review.status] ?? 0) + 1;

    // The id is used to size a set and is then discarded; it is never returned.
    const repositoriesReviewed = new Set(reviews.map(review => String(review.repositoryId))).size;

    // Execution time, not queue time: startedAt is stamped when a runner picks the review up, so
    // this measures BuildIT rather than however long a customer's queue was.
    //
    // Measured over reviews that actually ran the pipeline. A review that dies on an unreachable
    // sandbox is stamped started and completed milliseconds apart, so mixing those into the median
    // measures how fast BuildIT fails rather than how long a review takes - arithmetically true and
    // an answer to a question nobody asked. track-record.json records platform failures as a large
    // share of this deployment's history, which is exactly the size of population that would drag
    // the figure down. A duration is only meaningful for a run that did the work, so the statuses
    // that stop early are excluded and the page names the population it is describing.
    const ranToCompletion = new Set(["checks_passed", "changes_requested", "delivered", "inconclusive"]);
    // Over a recent window, not all of history, and the page says so.
    //
    // Two things drag a lifetime median away from describing the product. A review that dies on an
    // unreachable sandbox is stamped started and completed milliseconds apart, so the failure
    // population pulls the number toward zero; and the early development runs that make up most of
    // the history never executed a sandbox at all. Measured over everything, both the median and
    // the 95th percentile came out at 4ms while reviews running today take forty to forty-five
    // seconds - a number that is arithmetically defensible and tells the reader nothing true.
    //
    // `reviews` is already newest-first, so taking the head of the filtered list is the most recent
    // window rather than an arbitrary slice.
    const durationWindow = 25;
    const timed = reviews.filter(review => ranToCompletion.has(review.status)).slice(0, durationWindow);
    const durations = timed
      .map(review => review.startedAt !== undefined && review.completedAt !== undefined ? review.completedAt - review.startedAt : undefined)
      .filter((value): value is number => value !== undefined && value >= 0)
      .sort((a, b) => a - b);

    // kind "model_tokens" is the only priced kind; sandbox_seconds is recorded at unitCost 0. The
    // ledger's currency label is "provider_billed" because the spend lands on the customer's own
    // provider key, not on BuildIT - so this is what BuildIT's reviews have cost to run, and the
    // page has to say that rather than implying revenue.
    const modelRows = ledger.filter(row => row.kind === "model_tokens");
    const modelSpendUsd = modelRows.reduce((sum, row) => sum + rowCostUsd(row), 0);
    const modelTokens = modelRows.reduce((sum, row) => sum + row.quantity, 0);

    return {
      generatedAt: Date.now(),
      rowCeiling,
      reviews: {
        counted: reviews.length,
        truncated: reviews.length === rowCeiling,
        byStatus,
        repositoriesReviewed,
      },
      findings: {
        counted: findings.length,
        truncated: findings.length === rowCeiling,
      },
      spend: {
        modelSpendUsd,
        modelTokens,
        counted: ledger.length,
        truncated: ledger.length === rowCeiling,
      },
      durationMs: {
        sampleSize: durations.length,
        median: percentile(durations, 0.5),
        p95: percentile(durations, 0.95),
      },
    };
  },
});
