import { query } from "./_generated/server";
import { decisiveStatuses } from "./lib/reviewOutcome";
import { rowCostUsd } from "./lib/usageCost";

// BuildIT has no analytics, and every number it published about itself was a literal typed into a
// page - the exact rot track-record.mjs was written to stop, except that file is regenerated by
// hand and is a snapshot by the time anyone reads it. So a stranger evaluating BuildIT had to take
// the operating numbers on trust, which is the one thing this product exists to refuse.
//
// This is the live version: one unauthenticated query, aggregate counts only, read from the same
// production database the product runs on. It is declared "public_webhook" in
// publicFunctionPolicy.ts - the only authorization value that means "no identity required" - and
// its response is "metadata" because nothing it returns is derived from a customer's source.
//
// What it must never return, and the reason each one is missing rather than merely unused:
//   - repository owner/name, and the repositoryId itself: naming who BuildIT reviews for is a
//     customer disclosure, so only the count of distinct ids leaves this function.
//   - organizationId, organization name or slug, membership counts: same, one level up.
//   - triggerActor, cancelledBy, createdBy, or any other actor field: those are GitHub logins.
//   - finding text, path, ruleId, fingerprintHmac, severity per repository: findings are
//     source-derived, and a fingerprint is a stable identifier of one line of someone's code.
//   - headSha/baseSha/branch hashes: an sha is a join key back to a public repository.
//   - the ledger's currency label and per-organization spend: only one total in USD.
// Every value below is either a count, a duration, a sum, or a status literal from
// validators.ts - BuildIT's own enum, not customer data.

// Bounded for the same reason activation.ts is: this feeds a live subscription that re-executes on
// every matching write, and an unbounded read of an append-only table eventually crosses Convex's
// per-query read limit, where the query hard-fails rather than degrading. Newest-first, so a
// truncated answer is the recent window rather than an arbitrary slice - and `truncated` says so
// instead of letting a capped count read as a total.
const rowCeiling = 2_000;


export const summary = query({
  args: {},
  handler: async (ctx) => {
    const [reviewRows, findingRows, ledgerRows] = await Promise.all([
      ctx.db.query("reviews").order("desc").take(rowCeiling + 1),
      ctx.db.query("findings").order("desc").take(rowCeiling + 1),
      ctx.db.query("usageLedger").withIndex("by_time").order("desc").take(rowCeiling + 1),
    ]);

    const reviews = reviewRows.slice(0, rowCeiling), findings = findingRows.slice(0, rowCeiling), ledger = ledgerRows.slice(0, rowCeiling);
    const decisive = decisiveStatuses;
    const distinctCompletedPullRequests = new Set(reviews.filter(review => review.completedAt !== undefined && decisive.has(review.status)).map(review => `${review.repositoryId}:${review.prNumber}`)).size;

    // Present statuses only. Zero-filling the whole enum would put eighteen rows on the page,
    // most of them stating that something never happened.
    const byStatus: Record<string, number> = {};
    for (const review of reviews) byStatus[review.status] = (byStatus[review.status] ?? 0) + 1;

    // The id is used to size a set and is then discarded; it is never returned.
    const repositoriesReviewed = new Set(reviews.map(review => String(review.repositoryId))).size;

    // No duration statistic. It was on this page and it was wrong: verdict-reaching reviews showed
    // a median of 0.1s while platform failures showed 87s, because a review row's createdAt and
    // startedAt are both re-stamped per execution generation, so neither pair measures the wait a
    // person experienced. A latency number nobody can defend does not belong on a page whose whole
    // claim is that the numbers are checkable - so it is absent, and the absence is deliberate.

    // kind "model_tokens" is the only priced kind; sandbox_seconds is recorded at unitCost 0. The
    // ledger's currency label is "provider_billed" because the spend lands on the customer's own
    // provider key, not on BuildIT - so this is what BuildIT's reviews have cost to run, and the
    // page has to say that rather than implying revenue.
    const modelRows = ledger.filter(row => row.kind === "model_tokens");
    const modelSpendUsd = modelRows.reduce((sum, row) => sum + rowCostUsd(row), 0);
    const modelTokens = modelRows.reduce((sum, row) => sum + row.quantity, 0);

    return {
      generatedAt: Date.now(),
      rowCeiling,
      reviews: {
        counted: reviews.length,
        truncated: reviewRows.length > rowCeiling,
        distinctCompletedPullRequests,
        byStatus,
        repositoriesReviewed,
      },
      findings: {
        counted: findings.length,
        truncated: findingRows.length > rowCeiling,
      },
      spend: {
        costPending: modelRows.some(row => row.costStatus === "unknown"),
        modelSpendUsd,
        modelTokens,
        counted: ledger.length,
        truncated: ledgerRows.length > rowCeiling,
      },
    };
  },
});

// "Publish ten pull request links with timestamps and BuildIT's comments" is a fair ask: aggregate
// counts prove volume but not that any single review was real, and a screenshot proves neither.
//
// The hard part is that summary above refuses to name a repository on purpose - naming who BuildIT
// reviews for is a customer disclosure, and a repository being public does not make the commercial
// relationship public. A customer's open-source repo must not appear on this page because someone
// noticed it was world-readable.
//
// So the rule is narrower than "public": the repository is public AND its owner is an account
// BuildIT itself publishes evidence from. Those are snapshots of open-source projects, created by
// this project, reviewed by this project, for exactly this purpose. Publishing them discloses
// nothing about anybody else, and the moment a real customer connects a public repository it stays
// out of this list by default rather than by luck.
const evidenceOwners = new Set(["tanmayiift"]);

export const recentPublicReviews = query({
  args: {},
  handler: async ctx => {
    const repositoryLimit = 50, reviewsPerRepository = 100, listLimit = 40;
    const repositoryRows = (await Promise.all([...evidenceOwners].map(owner => ctx.db.query("repositories")
      .withIndex("by_owner_visibility", q => q.eq("owner", owner).eq("visibility", "public")).take(repositoryLimit + 1)))).flat();
    const repositories = repositoryRows.slice(0, repositoryLimit);
    const byId = new Map(repositories.map(item => [item._id, item]));
    const pages = await Promise.all(repositories.map(repository => ctx.db.query("reviews")
      .withIndex("by_repo_completed", q => q.eq("repositoryId", repository._id).gt("completedAt", undefined))
      .order("desc").take(reviewsPerRepository + 1)));
    const reviews = pages.flatMap((page, index) => page.slice(0, reviewsPerRepository)
      .filter(review => review.organizationId === repositories[index]!.organizationId));
    const latest = new Map<string, typeof reviews[number]>();
    for (const review of reviews) {
      const key = `${review.repositoryId}:${review.prNumber}`;
      const held = latest.get(key);
      if (!held || (review.completedAt ?? 0) > (held.completedAt ?? 0)) latest.set(key, review);
    }
    const partial = { repositories: repositoryRows.length > repositoryLimit, reviews: pages.some(page => page.length > reviewsPerRepository), list: latest.size > listLimit };
    return {
      generatedAt: Date.now(), repositoriesListed: byId.size,
      truncated: Object.values(partial).some(Boolean), partial,
      limits: { repositories: repositoryLimit, reviewsPerRepository, list: listLimit },
      reviews: [...latest.values()].sort((left, right) => (right.completedAt ?? 0) - (left.completedAt ?? 0)).slice(0, listLimit).map(review => {
        const repository = byId.get(review.repositoryId)!;
        return { owner: repository.owner, name: repository.name, prNumber: review.prNumber, status: review.status, completedAt: review.completedAt! };
      }),
    };
  },
});
