import { ConvexError, v } from "convex/values";
import { internalMutation, internalQuery } from "./_generated/server";
import { assertReviewParent } from "./lib/parentConsistency";
import { checkConclusion, checkKind } from "./validators";

const executionArgs = { organizationId: v.id("organizations"), reviewId: v.id("reviews"), expectedHeadSha: v.string(), expectedGeneration: v.number() };
const hash = v.string();

export const mode = internalQuery({args:executionArgs,handler:async(ctx,args)=>{const review=await assertReviewParent(ctx.db,args.organizationId,args.reviewId);if(review.headSha!==args.expectedHeadSha||review.executionGeneration!==args.expectedGeneration||review.isStale)throw new ConvexError("stale_or_replaced_review");return review.mode}});

export const scope = internalQuery({
  args: executionArgs,
  handler: async (ctx, args) => {
    const review = await assertReviewParent(ctx.db, args.organizationId, args.reviewId), repository = await ctx.db.get((await assertReviewParent(ctx.db, args.organizationId, args.reviewId)).repositoryId);
    const installation = repository ? await ctx.db.get(repository.installationId) : null;
    if (review.headSha !== args.expectedHeadSha || review.executionGeneration !== args.expectedGeneration || review.isStale || review.mode !== "autofix" || !["validating", "autofixing"].includes(review.status) || !["analysis", "autofix"].includes(review.currentStage)) throw new ConvexError("autofix_not_ready");
    if (!repository || !repository.enabled || repository.organizationId !== args.organizationId || review.isFork || repository.autofixMode !== "stacked" || !installation || installation.organizationId !== args.organizationId || installation.status !== "active") throw new ConvexError("autofix_delivery_unavailable");
    const artifacts = await ctx.db.query("artifacts").withIndex("by_review", q => q.eq("reviewId", review._id)).collect();
    const analysis = artifacts.find(item => item.type === "prompt_trace" && item.redactionStatus === "redacted" && !item.deletedAt && item.storageKey.endsWith("/analysis.json"));
    const contexts = artifacts.filter(item => item.type === "repository_snapshot" && item.redactionStatus === "redacted" && !item.deletedAt && /\/context-(?:base|head)-\d+\.json$/.test(item.storageKey));
    if (!analysis || !contexts.length || contexts.some(item => item.organizationId !== args.organizationId || item.repositoryId !== repository._id)) throw new ConvexError("autofix_evidence_unavailable");
    const rounds = await ctx.db.query("autofixRounds").withIndex("by_review_round", q => q.eq("reviewId", review._id)).collect(), attempts = await ctx.db.query("autofixAttempts").withIndex("by_review_attempt", q => q.eq("reviewId", review._id)).collect(), credentials = await ctx.db.query("providerCredentials").withIndex("by_org_status", q => q.eq("organizationId", args.organizationId).eq("status", "valid")).collect(), credential = credentials.find(item => item.repositoryId === repository._id && item.provider === review.provider) ?? credentials.find(item => item.repositoryId === undefined && item.provider === review.provider);
    if (!credential || !credential.lastValidatedAt) throw new ConvexError("provider_credential_invalid");
    return { organizationId: review.organizationId, repositoryId: repository._id, reviewId: review._id, installationId: installation.installationId, githubRepositoryId: repository.githubRepositoryId, prNumber: review.prNumber,
      headSha: review.headSha, baseSha: review.baseSha, createdAt: review.createdAt, configRevisionId: review.configRevisionId, runnerImageVersion: review.runnerImageVersion,
      analysis: { id: analysis._id, storageKey: analysis.storageKey, checksum: analysis.checksum, size: analysis.size },
      provider: review.provider, model: review.model, credentialDocumentId: credential._id, credential: { id: credential.credentialScopeId, organizationId: String(credential.organizationId), ...(credential.repositoryId ? { repositoryId: String(credential.repositoryId) } : {}), provider: credential.provider, ciphertext: credential.encryptedCiphertext, nonce: credential.nonce, tag: credential.authTag, wrappedDataKey: credential.wrappedDataKey, kmsKeyId: credential.kmsKeyId, envelopeVersion: credential.envelopeVersion, keyVersion: credential.keyVersion, aadDigest: credential.aadDigest, maskedSuffix: credential.maskedSuffix, status: "valid" as const, createdBy: credential.createdBy, createdAt: credential.createdAt, lastValidatedAt: credential.lastValidatedAt },
      contexts: contexts.map(item => ({ id: item._id, storageKey: item.storageKey, checksum: item.checksum, size: item.size })), patchFingerprints: attempts.map(item => item.patchFingerprint), rounds: rounds.map(item => { const validation = artifacts.find(artifact => artifact.type === "command_output" && artifact.redactionStatus === "redacted" && !artifact.deletedAt && artifact.storageKey.endsWith(`/autofix-${item.roundNumber}-validation.json`)); return { roundNumber: item.roundNumber, candidateCommitSha: item.candidateCommitSha, outcome: item.validationOutcome, ...(validation ? { validation: { id: validation._id, storageKey: validation.storageKey, checksum: validation.checksum, size: validation.size } } : {}) }; }) };
  },
});

export const recordModelUsage = internalMutation({
  args: { ...executionArgs, credentialId: v.id("providerCredentials"), inputTokens: v.number(), outputTokens: v.number(), now: v.number() },
  handler: async (ctx, args) => { const review = await assertReviewParent(ctx.db, args.organizationId, args.reviewId), credential = await ctx.db.get(args.credentialId), quantity = args.inputTokens + args.outputTokens; if (review.headSha !== args.expectedHeadSha || review.executionGeneration !== args.expectedGeneration || review.isStale || review.mode !== "autofix" || !credential || credential.organizationId !== args.organizationId || (credential.repositoryId && credential.repositoryId !== review.repositoryId) || credential.provider !== review.provider || credential.status !== "valid" || !Number.isSafeInteger(quantity) || quantity < 0) throw new ConvexError("autofix_model_usage_invalid"); await ctx.db.insert("usageLedger", { organizationId: args.organizationId, repositoryId: review.repositoryId, reviewId: review._id, kind: "model_tokens", quantity, unitCost: 0, currency: "provider_billed", occurredAt: args.now }); await ctx.db.patch(credential._id, { lastUsedAt: args.now }); },
});

export const reserveArtifact = internalMutation({
  args: { ...executionArgs, roundNumber: v.number(), slot: v.string(), type: v.union(v.literal("patch"), v.literal("command_output"), v.literal("review_message")), checksum: hash, size: v.number(), now: v.number() },
  handler: async (ctx, args) => {
    const review = await assertReviewParent(ctx.db, args.organizationId, args.reviewId);
    if (review.headSha !== args.expectedHeadSha || review.executionGeneration !== args.expectedGeneration || review.isStale || review.mode !== "autofix" || !Number.isInteger(args.roundNumber) || args.roundNumber < 1 || args.roundNumber > 3 || !/^[a-z0-9-]{1,40}$/.test(args.slot) || !/^[0-9a-f]{64}$/.test(args.checksum) || !Number.isInteger(args.size) || args.size < 1 || args.size > 4_000_000) throw new ConvexError("invalid_autofix_artifact");
    const suffix = `/autofix-${args.roundNumber}-${args.slot}.${args.type === "review_message" ? "md" : "json"}`;
    const prior = (await ctx.db.query("artifacts").withIndex("by_review", q => q.eq("reviewId", review._id)).collect()).find(item => item.storageKey.endsWith(suffix));
    if (prior) { if (prior.type !== args.type || prior.checksum !== args.checksum || prior.size !== args.size) throw new ConvexError("autofix_artifact_conflict"); return { artifactId: prior._id, storageKey: prior.storageKey }; }
    const artifactId = await ctx.db.insert("artifacts", { organizationId: args.organizationId, repositoryId: review.repositoryId, reviewId: review._id, type: args.type, storageKey: "pending", encrypted: true, checksum: args.checksum, size: args.size, redactionStatus: "pending", expiresAt: Math.min(review.expiresAt, args.now + 7 * 86_400_000), deletionAttempts: 0 });
    const storageKey = `artifacts/${args.organizationId}/${review.repositoryId}/${review._id}/${artifactId}${suffix}`;
    await ctx.db.patch(artifactId, { storageKey }); return { artifactId, storageKey };
  },
});

export const completeArtifact = internalMutation({
  args: { ...executionArgs, artifactId: v.id("artifacts"), checksum: hash, size: v.number() },
  handler: async (ctx, args) => { const review = await assertReviewParent(ctx.db, args.organizationId, args.reviewId), artifact = await ctx.db.get(args.artifactId); if (review.headSha !== args.expectedHeadSha || review.executionGeneration !== args.expectedGeneration || review.isStale || !artifact || artifact.organizationId !== args.organizationId || artifact.repositoryId !== review.repositoryId || artifact.reviewId !== review._id || artifact.checksum !== args.checksum || artifact.size !== args.size || artifact.deletedAt) throw new ConvexError("autofix_artifact_mismatch"); if (artifact.redactionStatus === "redacted") return artifact._id; if (artifact.redactionStatus !== "pending") throw new ConvexError("autofix_artifact_mismatch"); await ctx.db.patch(artifact._id, { redactionStatus: "redacted" }); return artifact._id; },
});

const summary = v.object({ commitSha: v.string(), planId: v.string(), kind: checkKind, required: v.boolean(), conclusion: checkConclusion, exitCode: v.optional(v.number()), durationMs: v.number(), commandFingerprint: hash, nameHash: hash, credentialTeardownProved: v.literal(true), sandboxStopped: v.literal(true) });
export const completeRound = internalMutation({
  args: { ...executionArgs, roundNumber: v.number(), candidateCommitSha: v.string(), patchFingerprint: hash, patchArtifactId: v.id("artifacts"), validationArtifactId: v.id("artifacts"), summaries: v.array(summary), outcome: v.union(v.literal("passed"), v.literal("failed"), v.literal("incomplete")), now: v.number() },
  handler: async (ctx, args) => {
    const review = await assertReviewParent(ctx.db, args.organizationId, args.reviewId), patch = await ctx.db.get(args.patchArtifactId), validation = await ctx.db.get(args.validationArtifactId);
    if (review.headSha !== args.expectedHeadSha || review.executionGeneration !== args.expectedGeneration || review.isStale || review.mode !== "autofix" || !/^[0-9a-f]{40}$/.test(args.candidateCommitSha) || !/^[0-9a-f]{64}$/.test(args.patchFingerprint) || !patch || !validation || patch.organizationId !== args.organizationId || validation.organizationId !== args.organizationId || patch.repositoryId !== review.repositoryId || validation.repositoryId !== review.repositoryId || patch.reviewId !== review._id || validation.reviewId !== review._id || patch.type !== "patch" || validation.type !== "command_output" || patch.redactionStatus !== "redacted" || validation.redactionStatus !== "redacted") throw new ConvexError("autofix_round_mismatch");
    const existing = await ctx.db.query("autofixRounds").withIndex("by_review_round", q => q.eq("reviewId", review._id).eq("roundNumber", args.roundNumber)).unique();
    if (existing) { if (existing.candidateCommitSha !== args.candidateCommitSha || existing.validationOutcome !== args.outcome) throw new ConvexError("autofix_round_conflict"); return existing._id; }
    const attemptId = await ctx.db.insert("autofixAttempts", { organizationId: args.organizationId, reviewId: review._id, attemptNumber: args.roundNumber, patchFingerprint: args.patchFingerprint, patchArtifactId: patch._id, outcome: "applied", promptVersion: "patch-v1", startedAt: args.now, completedAt: args.now });
    const roundId = await ctx.db.insert("autofixRounds", { organizationId: args.organizationId, reviewId: review._id, roundNumber: args.roundNumber, attemptId, candidateCommitSha: args.candidateCommitSha, validationScope: "final_validation", validationOutcome: args.outcome, completedValidation: true, startedAt: args.now, completedAt: args.now });
    if (!args.summaries.length || (args.outcome === "passed" && args.summaries.some(item => item.required && item.conclusion !== "passed"))) throw new ConvexError("autofix_summary_invalid");
    for (const item of args.summaries) { if (item.commitSha !== args.candidateCommitSha || !/^[0-9a-f]{64}$/.test(item.commandFingerprint) || !/^[0-9a-f]{64}$/.test(item.nameHash)) throw new ConvexError("autofix_summary_invalid"); await ctx.db.insert("checkRuns", { organizationId: args.organizationId, reviewId: review._id, roundId, kind: item.kind, nameHash: item.nameHash, required: item.required, status: "completed", conclusion: item.conclusion, commandFingerprint: item.commandFingerprint, commitSha: item.commitSha, ...(item.exitCode === undefined ? {} : { exitCode: item.exitCode }), durationMs: item.durationMs, artifactId: validation._id, credentialTeardownProved: item.credentialTeardownProved, sandboxStopped: item.sandboxStopped, ...(item.conclusion === "failed" ? { failureClass: "code" as const } : {}), startedAt: Math.max(0, args.now - item.durationMs), completedAt: args.now }); }
    await ctx.db.patch(review._id, { status: "autofixing", currentStage: "autofix", patchAttemptCount: args.roundNumber, completedRoundCount: args.roundNumber, updatedAt: args.now }); return roundId;
  },
});

export const completeDelivery = internalMutation({
  args: { ...executionArgs, roundNumber: v.number(), candidateCommitSha: v.string(), reportArtifactId: v.id("artifacts"), now: v.number() },
  handler: async (ctx, args) => {
    const review = await assertReviewParent(ctx.db, args.organizationId, args.reviewId), round = await ctx.db.query("autofixRounds").withIndex("by_review_round", q => q.eq("reviewId", review._id).eq("roundNumber", args.roundNumber)).unique(), report = await ctx.db.get(args.reportArtifactId);
    if (review.status === "delivered" && review.completedAt) return review._id;
    if (review.headSha !== args.expectedHeadSha || review.executionGeneration !== args.expectedGeneration || review.isStale || review.mode !== "autofix" || !round || round.candidateCommitSha !== args.candidateCommitSha || round.validationOutcome !== "passed" || !report || report.organizationId !== args.organizationId || report.repositoryId !== review.repositoryId || report.reviewId !== review._id || report.type !== "review_message" || report.redactionStatus !== "redacted" || report.deletedAt) throw new ConvexError("autofix_delivery_mismatch");
    const finalChecks = await ctx.db.query("checkRuns").withIndex("by_review_round", q => q.eq("reviewId", review._id).eq("roundId", round._id)).collect();
    if (!finalChecks.length || finalChecks.some(item => item.organizationId !== args.organizationId || item.commitSha !== args.candidateCommitSha || item.status !== "completed" || !item.artifactId || item.credentialTeardownProved !== true || item.sandboxStopped !== true) || finalChecks.some(item => item.required && item.conclusion !== "passed")) throw new ConvexError("autofix_delivery_evidence_incomplete");
    const effects = await ctx.db.query("githubSideEffects").withIndex("by_review", q => q.eq("reviewId", review._id)).collect(), required = ["branch_create", "stacked_pr_create", "check_update", "comment_update"];
    if (required.some(type => !effects.some(item => item.type === type && item.status === "completed" && item.externalId))) throw new ConvexError("autofix_delivery_incomplete");
    await ctx.db.patch(review._id, { status: "delivered", statusReasonCode: "delivery_complete", nextActionCode: "human_merge", githubCheckConclusion: "success", currentStage: "complete", completedAt: args.now, updatedAt: args.now });
    const existing = await ctx.db.query("reviewEvents").withIndex("by_review", q => q.eq("reviewId", review._id).eq("sequence", 5)).unique();
    if (!existing) await ctx.db.insert("reviewEvents", { organizationId: args.organizationId, reviewId: review._id, sequence: 5, type: "status_changed", stage: "complete", publicMessageArtifactId: report._id, internalCode: "autofix_delivery_complete", metadata: { count: args.roundNumber }, createdAt: args.now });
    const organization = await ctx.db.get(args.organizationId); if (!organization) throw new ConvexError("organization_unavailable");
    const metric = await ctx.db.query("metricEvents").withIndex("by_org_time", q => q.eq("organizationId", args.organizationId)).filter(q => q.and(q.eq(q.field("reviewId"), review._id),q.eq(q.field("name"), "autofix_applied"))).unique();
    if (!metric) await ctx.db.insert("metricEvents", { organizationId: args.organizationId, repositoryId: review.repositoryId, reviewId: review._id, name: "autofix_applied", value: 1, organizationTimezone: organization.timezone, occurredAt: args.now });
    return review._id;
  },
});

export const completeFailure = internalMutation({args:{...executionArgs,reportArtifactId:v.id("artifacts"),now:v.number()},handler:async(ctx,args)=>{const review=await assertReviewParent(ctx.db,args.organizationId,args.reviewId),report=await ctx.db.get(args.reportArtifactId),rounds=await ctx.db.query("autofixRounds").withIndex("by_review_round",q=>q.eq("reviewId",review._id)).collect(),effects=await ctx.db.query("githubSideEffects").withIndex("by_review",q=>q.eq("reviewId",review._id)).collect();if(review.status==="failed_after_bounds"&&review.completedAt)return review._id;if(review.headSha!==args.expectedHeadSha||review.executionGeneration!==args.expectedGeneration||review.isStale||review.mode!=="autofix"||rounds.length!==3||rounds.some(item=>item.validationOutcome==="passed")||!report||report.organizationId!==args.organizationId||report.repositoryId!==review.repositoryId||report.reviewId!==review._id||report.type!=="review_message"||report.redactionStatus!=="redacted"||report.deletedAt||!effects.some(item=>item.type==="comment_update"&&item.status==="completed"&&item.externalId))throw new ConvexError("autofix_failure_handoff_mismatch");await ctx.db.patch(review._id,{status:"failed_after_bounds",terminationBound:"round_limit",statusReasonCode:"final_validation_incomplete",nextActionCode:"inspect_findings",githubCheckConclusion:"failure",currentStage:"complete",completedAt:args.now,updatedAt:args.now});const event=await ctx.db.query("reviewEvents").withIndex("by_review",q=>q.eq("reviewId",review._id).eq("sequence",5)).unique();if(!event)await ctx.db.insert("reviewEvents",{organizationId:args.organizationId,reviewId:review._id,sequence:5,type:"status_changed",stage:"complete",publicMessageArtifactId:report._id,internalCode:"autofix_round_limit",metadata:{count:3},createdAt:args.now});return review._id}});

export const failPlatform = internalMutation({args:{...executionArgs,code:v.string(),now:v.number()},handler:async(ctx,args)=>{const review=await assertReviewParent(ctx.db,args.organizationId,args.reviewId);if(review.status==="delivered"||review.status==="failed_after_bounds")return review.status;if(review.headSha!==args.expectedHeadSha||review.executionGeneration!==args.expectedGeneration||review.isStale||review.mode!=="autofix"||!["validating","autofixing"].includes(review.status))throw new ConvexError("autofix_failure_mismatch");await ctx.db.patch(review._id,{status:"platform_failed",statusReasonCode:"platform_error",nextActionCode:"retry_review",currentStage:"complete",completedAt:args.now,updatedAt:args.now});return args.code.slice(0,80)}});
