import {posix} from "node:path";
export type ChangedFile={path:string;status:"added"|"modified"|"deleted"|"renamed";patch?:string;size:number;binary?:boolean;submodule?:boolean;lfsPointer?:boolean;generated?:boolean};
export type IndexedFile={path:string;status:ChangedFile["status"];symbols:string[];imports:string[];bytes:number};
export type Exclusion={path:string;reason:"path_invalid"|"binary"|"generated"|"submodule"|"lfs"|"file_too_large"|"budget_exhausted"|"patch_missing"};
const lockOrVendor=/(?:^|\/)(?:node_modules|vendor|dist|build|coverage)\/|(?:^|\/)(?:package-lock\.json|pnpm-lock\.yaml|yarn\.lock)$/i;
function safePath(path:string){const normalized=posix.normalize(path.replaceAll("\\","/"));return normalized&&!normalized.startsWith("../")&&!normalized.startsWith("/")&&!normalized.includes("\0")?normalized:null}
function symbols(text:string){const found=new Set<string>();for(const pattern of [/(?:function|class|interface|type|enum)\s+([A-Za-z_$][\w$]*)/g,/(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=/g,/^\s*(?:def|class)\s+([A-Za-z_]\w*)/gm,/(?:public|private|protected)?\s*(?:static\s+)?[\w<>,.?\[\]]+\s+([A-Za-z_]\w*)\s*\(/g])for(const match of text.matchAll(pattern))found.add(match[1]!);return[...found].sort()}
function imports(text:string){const found=new Set<string>();for(const pattern of [/\bfrom\s+["']([^"']+)["']/g,/\brequire\(["']([^"']+)["']\)/g,/^\s*(?:from|import)\s+([\w.]+)/gm,/^\s*import\s+[\w.*]+\s*;/gm])for(const match of text.matchAll(pattern))if(match[1])found.add(match[1]);return[...found].sort()}
export function buildContextIndex(files:ChangedFile[],limits={maxFiles:500,maxBytes:2_000_000,maxFileBytes:250_000}){const indexed:IndexedFile[]=[],excluded:Exclusion[]=[];let bytes=0;for(const file of [...files].sort((a,b)=>a.path.localeCompare(b.path))){const path=safePath(file.path);if(!path){excluded.push({path:file.path,reason:"path_invalid"});continue}let reason:Exclusion["reason"]|undefined;if(file.binary)reason="binary";else if(file.submodule)reason="submodule";else if(file.lfsPointer)reason="lfs";else if(file.generated||lockOrVendor.test(path))reason="generated";else if(file.size>limits.maxFileBytes)reason="file_too_large";else if(!file.patch&&file.status!=="deleted")reason="patch_missing";else if(indexed.length>=limits.maxFiles||bytes+file.size>limits.maxBytes)reason="budget_exhausted";if(reason){excluded.push({path,reason});continue}const patch=file.patch??"";indexed.push({path,status:file.status,symbols:symbols(patch),imports:imports(patch),bytes:file.size});bytes+=file.size}return{files:indexed,excluded,totalChangedFiles:files.length,indexedBytes:bytes,coverage:excluded.length?"partial" as const:"complete" as const}}
export function dependencyNeighborhood(index:ReturnType<typeof buildContextIndex>,path:string){const target=safePath(path);if(!target)return[];const stem=target.replace(/\.[^.]+$/,"");return index.files.filter(file=>file.path===target||file.imports.some(value=>value===stem||value.endsWith(`/${posix.basename(stem)}`))).map(file=>file.path)}
