import type {CheckResult} from "@buildit/runner";import {finalStatus} from "@buildit/runner";
export * from "./promptChain.js";
export * from "./reviewPlan.js";
export * from "./requirements.js";
export * from "./contextIndex.js";
export * from "./findings.js";
export * from "./report.js";
export * from "./modelChain.js";
export * from "./patchPolicy.js";
export type Evidence={id:string;path?:string;line?:number;searchScope?:string};
export type Finding={title:string;severity:"critical"|"warning"|"info";verdict:"covered"|"not_covered"|"unclear";evidenceId:string};
export function validateFindings(findings:Finding[],evidence:Evidence[]){const ids=new Set(evidence.map(e=>e.id));return findings.filter(f=>ids.has(f.evidenceId))}
export type Provider={review(input:{requirements:string[];diff:string;evidence:Evidence[]}):Promise<{findings:Finding[];tokens:number;cost:number}>};
export async function withRetry<T>(operation:()=>Promise<T>,options={max:5,baseMs:1},wait=(ms:number)=>new Promise(r=>setTimeout(r,ms))){let error:unknown;for(let i=0;i<=options.max;i++){try{return await operation()}catch(e){error=e;if(i===options.max)break;await wait(options.baseMs*2**i+Math.floor(Math.random()*options.baseMs))}}throw error}
export async function reviewWorkflow(provider:Provider,input:{requirements:string[];diff:string;evidence:Evidence[];checks:CheckResult[]}){const model=await withRetry(()=>provider.review({requirements:input.requirements,diff:input.diff,evidence:input.evidence}));const findings=validateFindings(model.findings,input.evidence);const checkStatus=finalStatus(input.checks);const status=checkStatus==="checks_passed"&&findings.some(f=>f.verdict==="not_covered")?"changes_requested":checkStatus;return{status,findings,tokens:model.tokens,cost:model.cost}}
export type EvidenceRecord={id:string;artifactExists:boolean;commitSha:string;path?:string;pathExists?:boolean;startLine?:number;endLine?:number;contentHash?:string;lineHashMatches?:boolean;stdout?:boolean;scannerParsed?:boolean;truncated:boolean};
export type MaterialClaim={text:string;evidenceIds:string[];certainty:"certain"|"uncertain"};
export function validEvidence(evidence:EvidenceRecord,pinnedCommit:string){if(!evidence.artifactExists||evidence.commitSha.toLowerCase()!==pinnedCommit.toLowerCase()||evidence.truncated)return false;if(evidence.path&&(evidence.pathExists!==true||!Number.isInteger(evidence.startLine)||!Number.isInteger(evidence.endLine)||evidence.startLine!<1||evidence.endLine!<evidence.startLine!||!evidence.contentHash||evidence.lineHashMatches!==true))return false;return true}
const forbiddenClaims=/\b(?:bug[- ]free|fully secure|repository[- ]wide coverage|all edge cases|guaranteed safe)\b/i;
export function gateClaims(claims:MaterialClaim[],evidence:EvidenceRecord[],pinnedCommit:string){const valid=new Set(evidence.filter(item=>validEvidence(item,pinnedCommit)).map(item=>item.id));return claims.filter(claim=>claim.text.trim().length>0&&!forbiddenClaims.test(claim.text)&&claim.evidenceIds.length>0&&claim.evidenceIds.every(id=>valid.has(id))).map(claim=>({...claim,text:claim.certainty==="uncertain"&&!/^uncertain:/i.test(claim.text)?`Uncertain: ${claim.text}`:claim.text}))}
export function verifiedCheckEvidence(evidence:EvidenceRecord){return evidence.stdout===true&&evidence.artifactExists&&!evidence.truncated}
export type ReviewCheckDecision={name:string;required:boolean;conclusion:"passed"|"failed"|"not_run"|"not_configured"|"timed_out"|"truncated"|"flaky";evidenceComplete:boolean;excerpt?:string};
// Kept consistent with reviewValidationData.finalizeDecision: these are two decision functions
// over the same facts, and this one writes the pull request comment.
export function computeReviewDecision(input:{isStale:boolean;environmentAvailable:boolean;coverageComplete?:boolean;injectionUnscoped?:boolean;checks:ReviewCheckDecision[];findings:Array<{resolution:"accepted"|"rejected"|"uncertain";blocking:boolean}>}){const required=input.checks.filter(check=>check.required),missing=required.filter(check=>!["passed","failed"].includes(check.conclusion)||!check.evidenceComplete),failed=required.filter(check=>check.conclusion==="failed"&&check.evidenceComplete),blocking=input.findings.filter(finding=>finding.resolution==="accepted"&&finding.blocking);if(input.isStale)return{status:"inconclusive" as const,reason:"stale_commit" as const,nextAction:"start_new_review" as const};if(!input.environmentAvailable)return{status:"inconclusive" as const,reason:"environment_unavailable" as const,nextAction:"retry_review" as const};if(input.injectionUnscoped)return{status:"inconclusive" as const,reason:"prompt_injection_unscoped" as const,nextAction:"human_merge" as const};if(input.coverageComplete===false)return{status:"inconclusive" as const,reason:"incomplete_coverage" as const,nextAction:"retry_review" as const};if(missing.length)return{status:"inconclusive" as const,reason:"required_check_missing" as const,nextAction:"retry_review" as const,missingChecks:missing.map(check=>check.name)};if(failed.length||blocking.length)return{status:"changes_requested" as const,reason:failed.length?"required_check_failed" as const:"blocking_findings" as const,nextAction:"inspect_findings" as const};return{status:"checks_passed" as const,reason:"checks_complete" as const,nextAction:"none" as const}}
