import type {CheckResult} from "@buildit/runner";import {finalStatus} from "@buildit/runner";
export * from "./promptChain.js";
export type Evidence={id:string;path?:string;line?:number;searchScope?:string};
export type Finding={title:string;severity:"critical"|"warning"|"info";verdict:"covered"|"not_covered"|"unclear";evidenceId:string};
export function validateFindings(findings:Finding[],evidence:Evidence[]){const ids=new Set(evidence.map(e=>e.id));return findings.filter(f=>ids.has(f.evidenceId))}
export type Provider={review(input:{requirements:string[];diff:string;evidence:Evidence[]}):Promise<{findings:Finding[];tokens:number;cost:number}>};
export async function withRetry<T>(operation:()=>Promise<T>,options={max:5,baseMs:1},wait=(ms:number)=>new Promise(r=>setTimeout(r,ms))){let error:unknown;for(let i=0;i<=options.max;i++){try{return await operation()}catch(e){error=e;if(i===options.max)break;await wait(options.baseMs*2**i+Math.floor(Math.random()*options.baseMs))}}throw error}
export async function reviewWorkflow(provider:Provider,input:{requirements:string[];diff:string;evidence:Evidence[];checks:CheckResult[]}){const model=await withRetry(()=>provider.review({requirements:input.requirements,diff:input.diff,evidence:input.evidence}));const findings=validateFindings(model.findings,input.evidence);const checkStatus=finalStatus(input.checks);const status=checkStatus==="checks_passed"&&findings.some(f=>f.verdict==="not_covered")?"changes_requested":checkStatus;return{status,findings,tokens:model.tokens,cost:model.cost}}
export type Bounds={rounds:number;attempts:number;diagnostics:number;providerRetries:number;commandRetries:number;spent:number;spendLimit:number};
export function nextAutofix(bounds:Bounds,patchFingerprint:string,seen:Set<string>){if(bounds.spent>=bounds.spendLimit)return{stop:true as const,status:"budget_exhausted" as const};if(seen.has(patchFingerprint))return{stop:true as const,status:"failed_after_bounds" as const,terminationBound:"repeated_patch" as const};if(bounds.rounds>=3)return{stop:true as const,status:"failed_after_bounds" as const,terminationBound:"round_limit" as const};if(bounds.attempts>=6)return{stop:true as const,status:"failed_after_bounds" as const,terminationBound:"attempt_limit" as const};seen.add(patchFingerprint);return{stop:false as const}}
export function deliveryAllowed(input:{allRequiredChecksPassed:boolean;headStillCurrent:boolean;isFork:boolean}){return input.allRequiredChecksPassed&&input.headStillCurrent&&!input.isFork}
