import {createHash} from "node:crypto";
export type RequirementSourceType="pull_request"|"github_issue"|"linear"|"jira"|"repository_document"|"test";
export type RequirementSourceStatus="available"|"missing"|"inaccessible"|"image_only"|"oversized";
export type RequirementSource={id:string;type:RequirementSourceType;url:string;version:string;fetchedAt:number;status:RequirementSourceStatus;content?:string};
export type AtomicRequirement={id:string;text:string;sourceId:string;line:number;evidenceHash:string;certainty:"explicit"|"unclear"};
export type RequirementConflict={canonical:string;requirementIds:string[];sourceIds:string[]};
export type DiscoveredLink={type:"github_issue"|"linear"|"jira";url:string};
const absolute=/(https?:\/\/(?:github\.com\/[^\s/]+\/[^\s/]+\/(?:issues|pull)\/\d+|linear\.app\/[^\s)]+|[^\s/]*atlassian\.net\/browse\/[A-Z][A-Z0-9]+-\d+))/gi;
export function discoverRequirementLinks(body:string,repositoryUrl:string):DiscoveredLink[]{const links=new Map<string,DiscoveredLink>();for(const match of body.matchAll(absolute)){const url=match[1]!.replace(/[.,;:]+$/g,"");const type=url.includes("github.com/")?"github_issue":url.includes("linear.app/")?"linear":"jira";links.set(url,{type,url})}for(const match of body.matchAll(/(?:^|[\s(])#(\d+)\b/gm)){const url=`${repositoryUrl.replace(/\/$/,"")}/issues/${match[1]}`;links.set(url,{type:"github_issue",url})}return[...links.values()]}
function hash(value:string){return createHash("sha256").update(value).digest("hex")}
export function extractAtomicRequirements(source:RequirementSource):AtomicRequirement[]{if(source.status!=="available"||!source.content)return[];const lines=source.content.split(/\r?\n/),requirements:AtomicRequirement[]=[];let section=false;for(let index=0;index<lines.length;index++){const raw=lines[index]!,trimmed=raw.trim();if(/^#{1,6}\s+(?:acceptance criteria|requirements?|expected behavio(?:u)?r)\b/i.test(trimmed)){section=true;continue}if(section&&/^#{1,6}\s+/.test(trimmed)){section=false;continue}const match=trimmed.match(/^(?:[-*+]\s+(?:\[[ xX]\]\s*)?|\d+[.)]\s+)(.+)$/);if(!match||(!section&&!/^[-*+]\s+\[[ xX]\]/.test(trimmed)))continue;const text=match[1]!.trim();if(!text||/^https?:\/\//.test(text))continue;requirements.push({id:`req-${source.id}-${index+1}`,text,sourceId:source.id,line:index+1,evidenceHash:hash(`${source.version}:${index+1}:${text}`),certainty:/\b(?:tbd|unclear|maybe|to be decided)\b/i.test(text)?"unclear":"explicit"})}return requirements}
const documentPath=/(?:^|\/)(?:README|CONTRIBUTING|SECURITY|REQUIREMENTS|SPEC)(?:\.[^/]*)?\.md$|^docs\/.*\.md$|^\.github\/PULL_REQUEST_TEMPLATE(?:\/.*|\.md)$/i;
const testPath=/(?:^|\/)(?:test|tests|spec|specs|__tests__)(?:\/|$)|\.(?:test|spec)\.[cm]?[jt]sx?$|^features\/.*\.feature$/i;
const configPath=/(?:^|\/)(?:buildit|review|quality)\.config\.[cm]?[jt]s$|^\.buildit(?:\.ya?ml|\.json)?$|^(?:package\.json|pyproject\.toml|pom\.xml|build\.gradle(?:\.kts)?)$/i;
export function repositoryRequirementSources(input:{files:Array<{path:string;content:string}>;headSha:string;now:number;maxTotalBytes?:number;maxFileBytes?:number;maxFiles?:number}){const maxTotal=input.maxTotalBytes??200_000,maxFile=input.maxFileBytes??50_000,maxFiles=input.maxFiles??40;if(!/^[0-9a-f]{40}$/i.test(input.headSha)||maxTotal<1||maxFile<1||maxFiles<1)throw new Error("invalid_repository_requirement_limits");const sources:RequirementSource[]=[],omitted:Array<{path:string;reason:"oversized"|"budget"}>=[];let remaining=maxTotal;for(const file of [...input.files].sort((a,b)=>a.path.localeCompare(b.path))){const type:RequirementSourceType=documentPath.test(file.path)||configPath.test(file.path)?"repository_document":testPath.test(file.path)?"test":"pull_request";if(type==="pull_request")continue;if(sources.length>=maxFiles){omitted.push({path:file.path,reason:"budget"});continue}const bytes=Buffer.byteLength(file.content),version=`${input.headSha}:${hash(`${file.path}\0${file.content}`)}`;if(bytes>maxFile){sources.push({id:`repo-${hash(file.path).slice(0,16)}`,type,url:`repository://${file.path}`,version,fetchedAt:input.now,status:"oversized"});omitted.push({path:file.path,reason:"oversized"});continue}if(bytes>remaining){omitted.push({path:file.path,reason:"budget"});continue}remaining-=bytes;sources.push({id:`repo-${hash(file.path).slice(0,16)}`,type,url:`repository://${file.path}`,version,fetchedAt:input.now,status:"available",content:file.content})}return{sources,omitted,coverage:omitted.length?"partial" as const:"complete" as const}}
export function findRequirementConflicts(requirements:AtomicRequirement[]):RequirementConflict[]{const groups=new Map<string,Array<AtomicRequirement&{negative:boolean}>>();for(const item of requirements){const negative=/\b(?:must|should|do|does|is|are|can)?\s*(?:not|never)\b|\bno\b/i.test(item.text),canonical=item.text.toLowerCase().replace(/\b(?:must|should|do|does|is|are|can|not|never|no)\b/g," ").replace(/[^a-z0-9]+/g," ").trim();if(!canonical)continue;groups.set(canonical,[...(groups.get(canonical)??[]),{...item,negative}])}return[...groups.entries()].flatMap(([canonical,items])=>new Set(items.map(item=>item.negative)).size>1?[{canonical,requirementIds:items.map(item=>item.id),sourceIds:[...new Set(items.map(item=>item.sourceId))]}]:[])}
export type RequirementFetcher=(link:DiscoveredLink)=>Promise<{status:RequirementSourceStatus;version:string;content?:string}>;
export async function acquireRequirements(input:{prBody:string;prUrl:string;repositoryUrl:string;headSha:string;now:number;maxSourceBytes:number;fetch:RequirementFetcher;repositorySources?:RequirementSource[]}){const prOversized=Buffer.byteLength(input.prBody)>input.maxSourceBytes,pr:RequirementSource={id:"pr-body",type:"pull_request",url:input.prUrl,version:input.headSha,fetchedAt:input.now,status:prOversized?"oversized":"available",...(prOversized?{}:{content:input.prBody})},sources=[pr];for(const [index,link] of discoverRequirementLinks(input.prBody,input.repositoryUrl).entries()){try{const fetched=await input.fetch(link),oversized=Boolean(fetched.content&&Buffer.byteLength(fetched.content)>input.maxSourceBytes);sources.push({id:`linked-${index+1}`,type:link.type,url:link.url,version:fetched.version,fetchedAt:input.now,status:oversized?"oversized":fetched.status,...(!oversized&&fetched.content!==undefined?{content:fetched.content}:{})})}catch{sources.push({id:`linked-${index+1}`,type:link.type,url:link.url,version:"unavailable",fetchedAt:input.now,status:"inaccessible"})}}sources.push(...(input.repositorySources??[]));const requirements=sources.flatMap(extractAtomicRequirements),conflicts=findRequirementConflicts(requirements);return{sources,requirements,conflicts,coverage:sources.some(source=>source.status!=="available")||conflicts.length?"partial" as const:"complete" as const}}
