import {createHash} from "node:crypto";
export type RequirementSourceType="pull_request"|"github_issue"|"linear"|"jira"|"repository_document";
export type RequirementSourceStatus="available"|"missing"|"inaccessible"|"image_only"|"oversized";
export type RequirementSource={id:string;type:RequirementSourceType;url:string;version:string;fetchedAt:number;status:RequirementSourceStatus;content?:string};
export type AtomicRequirement={id:string;text:string;sourceId:string;line:number;evidenceHash:string;certainty:"explicit"|"unclear"};
export type DiscoveredLink={type:Exclude<RequirementSourceType,"pull_request"|"repository_document">;url:string};
const absolute=/(https?:\/\/(?:github\.com\/[^\s/]+\/[^\s/]+\/(?:issues|pull)\/\d+|linear\.app\/[^\s)]+|[^\s/]*atlassian\.net\/browse\/[A-Z][A-Z0-9]+-\d+))/gi;
export function discoverRequirementLinks(body:string,repositoryUrl:string):DiscoveredLink[]{const links=new Map<string,DiscoveredLink>();for(const match of body.matchAll(absolute)){const url=match[1]!.replace(/[.,;:]+$/g,"");const type=url.includes("github.com/")?"github_issue":url.includes("linear.app/")?"linear":"jira";links.set(url,{type,url})}for(const match of body.matchAll(/(?:^|[\s(])#(\d+)\b/gm)){const url=`${repositoryUrl.replace(/\/$/,"")}/issues/${match[1]}`;links.set(url,{type:"github_issue",url})}return[...links.values()]}
function hash(value:string){return createHash("sha256").update(value).digest("hex")}
export function extractAtomicRequirements(source:RequirementSource):AtomicRequirement[]{if(source.status!=="available"||!source.content)return[];const lines=source.content.split(/\r?\n/),requirements:AtomicRequirement[]=[];let section=false;for(let index=0;index<lines.length;index++){const raw=lines[index]!,trimmed=raw.trim();if(/^#{1,6}\s+(?:acceptance criteria|requirements?|expected behavio(?:u)?r)\b/i.test(trimmed)){section=true;continue}if(section&&/^#{1,6}\s+/.test(trimmed)){section=false;continue}const match=trimmed.match(/^(?:[-*+]\s+(?:\[[ xX]\]\s*)?|\d+[.)]\s+)(.+)$/);if(!match||(!section&&!/^[-*+]\s+\[[ xX]\]/.test(trimmed)))continue;const text=match[1]!.trim();if(!text||/^https?:\/\//.test(text))continue;requirements.push({id:`req-${source.id}-${index+1}`,text,sourceId:source.id,line:index+1,evidenceHash:hash(`${source.version}:${index+1}:${text}`),certainty:/\b(?:tbd|unclear|maybe|to be decided)\b/i.test(text)?"unclear":"explicit"})}return requirements}
export type RequirementFetcher=(link:DiscoveredLink)=>Promise<{status:RequirementSourceStatus;version:string;content?:string}>;
export async function acquireRequirements(input:{prBody:string;prUrl:string;repositoryUrl:string;headSha:string;now:number;maxSourceBytes:number;fetch:RequirementFetcher}){const prOversized=Buffer.byteLength(input.prBody)>input.maxSourceBytes,pr:RequirementSource={id:"pr-body",type:"pull_request",url:input.prUrl,version:input.headSha,fetchedAt:input.now,status:prOversized?"oversized":"available",...(prOversized?{}:{content:input.prBody})},sources=[pr];for(const [index,link] of discoverRequirementLinks(input.prBody,input.repositoryUrl).entries()){try{const fetched=await input.fetch(link),oversized=Boolean(fetched.content&&Buffer.byteLength(fetched.content)>input.maxSourceBytes);sources.push({id:`linked-${index+1}`,type:link.type,url:link.url,version:fetched.version,fetchedAt:input.now,status:oversized?"oversized":fetched.status,...(!oversized&&fetched.content!==undefined?{content:fetched.content}:{})})}catch{sources.push({id:`linked-${index+1}`,type:link.type,url:link.url,version:"unavailable",fetchedAt:input.now,status:"inaccessible"})}}return{sources,requirements:sources.flatMap(extractAtomicRequirements),coverage:sources.some(source=>source.status!=="available")?"partial" as const:"complete" as const}}
