"use client";
import { useConvexAuth, useQuery } from "convex/react";
import { makeFunctionReference } from "convex/server";
import { useSampleTour } from "./workspace-route-boundary";
type Connection = { organization: null | { id: string; name: string } };
const connectionQuery = makeFunctionReference<"query", Record<string, never>, Connection>("repositoryConnections:current"), metricsQuery = makeFunctionReference<"query", { organizationId: string; since: number }, Record<string, number>>("metrics:summarize"), usageQuery = makeFunctionReference<"query", { organizationId: string; since: number }, { quantities: Record<string, number>; costs: Record<string, number>; recordCount: number; monthlyBudget: number }>("usage:summarize");
const sunday = () => { const date = new Date(), day = date.getDay(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - day); return date.getTime(); };
export function WorkspaceMetrics() { const tour = useSampleTour(), { isAuthenticated } = useConvexAuth(), connection = useQuery(connectionQuery, !tour && isAuthenticated ? {} : "skip"), since = sunday(), totals = useQuery(metricsQuery, connection?.organization ? { organizationId: connection.organization.id, since } : "skip"); if (tour) return <NoLiveData noun="metrics"/>; if (!connection?.organization || totals === undefined) return <Loading noun="metrics"/>; return <><div className="metric-line"><Metric title="PRs reviewed" value={totals.review_completed ?? 0} detail="Completed since Sunday" hero/><Metric title="Regressions caught" value={totals.ci_regression_caught ?? 0} detail="Base passed, head failed"/><Metric title="Verified Autofixes" value={totals.autofix_applied ?? 0} detail="Delivered after final checks"/><Metric title="Runner failures" value={totals.runner_failure ?? 0} detail="Platform failures, never passes"/></div><section className="metric-explainer"><div><p className="eyebrow">Accuracy</p><h2>Not reported without human labels</h2><p>Operational totals are live. Precision and recall remain hidden until a blind, adjudicated evaluation run meets the release sample threshold.</p></div><div className="formula"><span>Provider failures</span><strong>{totals.provider_failure ?? 0}</strong><small>Since Sunday</small></div><div className="formula"><span>Stale reviews</span><strong>{totals.stale_review ?? 0}</strong><small>Never counted as passed</small></div></section></>; }
export function WorkspaceUsage() { const tour = useSampleTour(), { isAuthenticated } = useConvexAuth(), connection = useQuery(connectionQuery, !tour && isAuthenticated ? {} : "skip"), since = new Date(new Date().getFullYear(), new Date().getMonth(), 1).getTime(), usage = useQuery(usageQuery, connection?.organization ? { organizationId: connection.organization.id, since } : "skip"); if (tour) return <NoLiveData noun="usage"/>; if (!connection?.organization || usage === undefined) return <Loading noun="usage"/>; const q = usage.quantities, knownCost = Object.entries(usage.costs).filter(([currency]) => currency !== "provider_billed").reduce((sum, [, value]) => sum + value, 0), percent = usage.monthlyBudget > 0 ? Math.min(100, knownCost / usage.monthlyBudget * 100) : 0; return <><section className="budget-board"><div><p className="eyebrow">Current month · {connection.organization.name}</p><strong>{knownCost.toFixed(2)} <small>of {usage.monthlyBudget.toFixed(2)} configured budget units</small></strong><div className="budget-track"><span style={{ width: `${percent}%` }}/></div><p>{(q.model_tokens ?? 0).toLocaleString()} model tokens · {(q.sandbox_seconds ?? 0).toLocaleString()} sandbox seconds · {(q.storage_bytes ?? 0).toLocaleString()} storage bytes</p></div><aside><strong>{usage.recordCount} source-free ledger records</strong><p>The organization has not configured a currency label. Provider-billed keys are reported as tokens unless the provider supplies trusted cost.</p></aside></section><section className="empty-band"><div><strong>Budget gate remains fail-closed</strong><p>A review does not start when its estimate exceeds the remaining ceiling. Partial work is never called a pass.</p></div><a href="/integrations">Manage provider →</a></section></>; }
function Metric({ title, value, detail, hero = false }: { title: string; value: number; detail: string; hero?: boolean }) { return <article className={`metric${hero ? " hero-metric" : ""}`}><span>{title}</span><strong>{value.toLocaleString()}</strong><small>{detail}</small></article>; }
function Loading({ noun }: { noun: string }) { return <section className="live-state" aria-live="polite"><span className="state-pulse"/><div><strong>Loading live {noun}…</strong><p>Checking the active organization on the server.</p></div></section>; }
function NoLiveData({ noun }: { noun: string }) { return <section className="empty-state compact-empty"><span className="empty-mark">—</span><h2>No sample {noun} are shown</h2><p>Connect a workspace to see tenant-scoped records. BuildIT does not present illustrative activity as customer data.</p></section>; }
