"use client";
import { useConvexAuth, useQuery } from "convex/react";
import { makeFunctionReference } from "convex/server";
import { NoActiveWorkspace } from "./no-active-workspace";
import { useSampleTour } from "./workspace-route-boundary";
import { auditActionLabel, auditResultLabel } from "./workspace-labels";
import { StatePanel } from "./state-panel";
import { EmptyState } from "./empty-state";
type Connection = { organization: null | { id: string; name: string } };
type Audit = { chainValid: boolean; truncated: boolean; events: Array<{ id: string; actorIdHash: string; action: string; resourceType: string; resourceFingerprint: string; result: string; createdAt: number }> };
const connectionQuery = makeFunctionReference<"query", Record<string, never>, Connection>("repositoryConnections:current"), auditQuery = makeFunctionReference<"query", { organizationId: string; limit: number }, Audit>("audit:list"), tone = (value: string) => value === "allowed" ? "success" : value === "denied" ? "warning" : "danger";
export function WorkspaceAudit() { const tour = useSampleTour(), { isAuthenticated } = useConvexAuth(), connection = useQuery(connectionQuery, !tour && isAuthenticated ? {} : "skip"), audit = useQuery(auditQuery, connection?.organization ? { organizationId: connection.organization.id, limit: 100 } : "skip"); if (tour) return <EmptyState mark="—" title="No sample security events" detail="Audit history appears only from a connected organization. Illustrative events are not presented as evidence." />; if (connection && !connection.organization) return <NoActiveWorkspace heading="No workspace is active yet" detail="The audit chain is kept per workspace, so there is no history to verify until one is active." />; if (!connection?.organization || audit === undefined) return <StatePanel loading title="Loading source-free audit history…" detail="Checking the active organization and event chain." />; if (!audit.events.length) return <EmptyState mark="0" title="No security actions recorded yet" detail="Credential, membership, review, and delivery actions will appear here without source content." />; return <><div className={`boundary-note${audit.chainValid ? "" : " danger"}`}><strong>{audit.chainValid ? "Audit chain verified" : "Audit chain verification failed"}</strong><br/>{audit.chainValid ? `All ${audit.events.length} displayed events link to the preceding event hash.` : "Do not rely on this history until an administrator investigates."}{audit.truncated ? " Verification was limited to the newest 1,000 records." : ""}</div><section className="audit-preview">{audit.events.map(event => <div className="audit-row" key={event.id}><time>{new Date(event.createdAt).toLocaleString()}</time><span>{auditActionLabel(event.action)} <code>{event.action}</code></span><span>{event.resourceType} · {event.resourceFingerprint} · actor {event.actorIdHash.slice(0, 8)}</span><span className={`status ${tone(event.result)}`}>{auditResultLabel(event.result)}</span></div>)}</section></>; }
