"use client";
import {useConvexAuth,useMutation,useQuery} from "convex/react";
import {useAuthToken} from "@convex-dev/auth/react";
import {makeFunctionReference} from "convex/server";
import {type FormEvent,useEffect,useState} from "react";
type Provider="anthropic"|"openai"|"gemini";
type Connection={organization:null|{id:string;name:string;role:string};repositories:Array<{id:string;owner:string;name:string}>};
type SavedCredential={id:string;provider:Provider;maskedSuffix:string;status:string;lastValidatedAt:number};
const connectionQuery=makeFunctionReference<"query",Record<string,never>,Connection>("repositoryConnections:current");
const credentialsQuery=makeFunctionReference<"query",{organizationId:string},SavedCredential[]>("integrations:listProviderCredentials");
const revokeMutation=makeFunctionReference<"mutation",{organizationId:string;credentialId:string;requestId:string},{id:string;status:"revoked"}>("integrations:revokeProviderCredential");
const names:Record<Provider,string>={anthropic:"Anthropic",openai:"OpenAI",gemini:"Google Gemini"};
function safeMessage(code:string){if(code==="invalid_key")return "That provider rejected the key. Check its API access, then try again.";if(code==="recent_reauthentication_required")return "For security, sign in with GitHub again before saving a key.";if(code==="not_found_or_forbidden")return "Your access changed. Refresh and check the active organization.";return "The secure key service could not save this key. The key was not stored; try again shortly."}
export function ModelKeyForm(){
 const[hydrated,setHydrated]=useState(false),{isAuthenticated,isLoading}=useConvexAuth(),token=useAuthToken(),connection=useQuery(connectionQuery,hydrated&&isAuthenticated?{}:"skip"),organization=connection?.organization,canManage=organization?.role==="owner"||organization?.role==="admin",credentials=useQuery(credentialsQuery,canManage&&organization?{organizationId:organization.id}:"skip"),revokeCredential=useMutation(revokeMutation),[provider,setProvider]=useState<Provider>("anthropic"),[repositoryId,setRepositoryId]=useState(""),[apiKey,setApiKey]=useState(""),[working,setWorking]=useState(false),[result,setResult]=useState<{kind:"success"|"error";text:string}|null>(null),brokerUrl=process.env.NEXT_PUBLIC_BROKER_URL;
 useEffect(()=>setHydrated(true),[]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token||!organization||!brokerUrl||!apiKey)return;const key=apiKey,repo=connection?.repositories.find(item=>item.id===repositoryId),scope=repo?`${organization.name} → ${repo.owner}/${repo.name}`:`${organization.name} → all connected repositories`;setApiKey("");setWorking(true);setResult(null);try{const response=await fetch(`${brokerUrl.replace(/\/$/,"")}/api/credentials`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({organizationId:organization.id,...(repositoryId?{repositoryId}:{}),provider,apiKey:key})});const body=await response.json() as{error?:string;credential?:{maskedSuffix:string}};if(!response.ok)throw new Error(body.error??"credential_save_failed");setResult({kind:"success",text:`${names[provider]} key ending in ${body.credential?.maskedSuffix??"••••"} was validated, encrypted, and saved for ${scope}.`})}catch(error){setResult({kind:"error",text:safeMessage(error instanceof Error?error.message:"credential_save_failed")})}finally{setWorking(false)}}
 async function revoke(credential:SavedCredential){if(!organization||credential.status==="revoked")return;setWorking(true);setResult(null);try{await revokeCredential({organizationId:organization.id,credentialId:credential.id,requestId:`credential-revoke-${crypto.randomUUID()}`});setResult({kind:"success",text:`${names[credential.provider]} key ending in ${credential.maskedSuffix} was revoked. BuildIT will not use it again.`})}catch(error){setResult({kind:"error",text:safeMessage(error instanceof Error?error.message:"credential_save_failed")})}finally{setWorking(false)}}
 if(!hydrated||isLoading||(isAuthenticated&&!connection))return <section className="setup-card" aria-live="polite"><h2>Secure model connection</h2><p>Checking your account and organization…</p></section>;
 if(!isAuthenticated)return <section className="setup-card"><Heading/><div className="credential-state"><strong>Sign in before adding a key</strong><p>This binds the encrypted credential to one verified organization. Signing in alone does not grant repository access.</p><a className="button" href="/sign-in?returnTo=%2Fsetup%2Fmodel">Sign in with GitHub</a></div><Boundary/></section>;
 if(!organization)return <section className="setup-card"><h2>Choose an organization first</h2><p>Connect or select an organization so BuildIT keeps this key in the correct security boundary.</p><a className="button" href="/setup/install">Connect GitHub</a><Boundary/></section>;
 if(!canManage)return <section className="setup-card"><h2>An Admin or Owner manages model keys</h2><p>Your {organization.role} access cannot add or replace credentials.</p><Boundary/></section>;
 return <section className="setup-card"><Heading/><form className="credential-form" onSubmit={save}><div className="credential-grid"><label className="field"><span>Provider</span><select value={provider} onChange={event=>setProvider(event.target.value as Provider)}><option value="anthropic">Anthropic</option><option value="openai">OpenAI</option><option value="gemini">Google Gemini</option></select></label><label className="field"><span>Repository scope</span><select value={repositoryId} onChange={event=>setRepositoryId(event.target.value)}><option value="">All repositories in {organization.name}</option>{connection.repositories.map(repo=><option key={repo.id} value={repo.id}>{repo.owner}/{repo.name}</option>)}</select></label></div><div className="scope-trail" aria-label="Credential scope"><span>Organization</span><strong>{organization.name}</strong><b>→</b><span>Repository</span><strong>{repositoryId?connection.repositories.find(item=>item.id===repositoryId)?.name:"All connected"}</strong></div><label className="field"><span>{names[provider]} API key</span><input type="password" autoComplete="off" value={apiKey} onChange={event=>setApiKey(event.target.value)} placeholder="Paste key to validate and encrypt" required minLength={16} disabled={working}/></label><button className="button" type="submit" disabled={working||!apiKey||!brokerUrl}>{working?"Validating and encrypting…":"Validate and save key"}</button>{!brokerUrl?<p className="form-result error" role="alert">Secure key storage is not configured for this environment.</p>:null}{result?<p className={`form-result ${result.kind}`} role={result.kind==="error"?"alert":"status"}>{result.text}</p>:null}</form>{credentials?.length?<div className="saved-credentials"><h3>Saved for this organization</h3>{credentials.map(credential=><div key={credential.id}><span className="provider-mark">{names[credential.provider].slice(0,2).toUpperCase()}</span><span><strong>{names[credential.provider]} · •••• {credential.maskedSuffix}</strong><small>{credential.status} · validated {new Date(credential.lastValidatedAt).toLocaleDateString()}</small></span><button className="button secondary compact" type="button" disabled={working||credential.status==="revoked"} onClick={()=>void revoke(credential)}>{credential.status==="revoked"?"Revoked":"Revoke"}</button></div>)}</div>:null}<Boundary/></section>}
function Heading(){return <div className="optional-heading"><div><h2>Bring your own model key</h2><p>The key is requested only when you choose AI analysis or Autofix.</p></div><span className="status neutral">Optional now</span></div>}
function Boundary(){return <div className="boundary-note"><strong>Security boundary</strong><br/>The raw key goes directly from this browser to BuildIT’s separate credential broker. It is validated, encrypted with AWS KMS in Ireland, and never returned to the browser or stored in Convex as plaintext.</div>}
