export type CheckKind="test"|"lint"|"typecheck"|"build"|"static_analysis"|"dependency_audit"|"secret_scan";
export type CheckConclusion="passed"|"failed"|"not_run"|"timed_out"|"truncated";
export type NamedCommand="install"|"test"|"lint"|"typecheck"|"build";
export type PackageManager="npm"|"pnpm"|"yarn";
export type CommandPlan={planId:NamedCommand;origin:"built_in"|"trusted_ref";kind:CheckKind;executable:PackageManager;args:string[];required:boolean;timeoutMs:number;cpuLimit:number;memoryMb:number;outputBytes:number;fileBytes:number;network:"none"|"registry_only"};
export type CheckResult=CommandPlan&{conclusion:CheckConclusion;exitCode?:number;durationMs:number;failureClass?:"code"|"environment"|"tooling_missing"|"timeout"|"resource_limit"|"network_blocked"|"platform"};
export const SERVERLESS_PLAN_BUDGET_MS=150_000;
export const SANDBOX_DIAGNOSTIC_RERUN_LIMIT=1;
export const SERVERLESS_SANDBOX_WORK_BUDGET_MS=180_000;
export const SANDBOX_SCANNER_TIMEOUT_MS=35_000;
export const SANDBOX_OVERHEAD_RESERVE_MS=55_000;
const commands:Record<PackageManager,Record<NamedCommand,string[]>>={npm:{install:["ci","--ignore-scripts","--no-audit"],test:["run","test"],lint:["run","lint"],typecheck:["run","typecheck"],build:["run","build"]},pnpm:{install:["install","--frozen-lockfile","--ignore-scripts"],test:["run","test"],lint:["run","lint"],typecheck:["run","typecheck"],build:["run","build"]},yarn:{install:["install","--immutable","--mode=skip-builds"],test:["run","test"],lint:["run","lint"],typecheck:["run","typecheck"],build:["run","build"]}};
const kinds:Record<NamedCommand,CheckKind>={install:"build",test:"test",lint:"lint",typecheck:"typecheck",build:"build"};
export function createNamedPlan(input:{planId:NamedCommand;manager:PackageManager;origin:"built_in"|"trusted_ref";required:boolean}):CommandPlan{return validatePlan({planId:input.planId,origin:input.origin,kind:kinds[input.planId],executable:input.manager,args:[...commands[input.manager][input.planId]],required:input.required,timeoutMs:input.planId==="install"?600_000:1_200_000,cpuLimit:2,memoryMb:4096,outputBytes:10_000_000,fileBytes:1_000_000_000,network:input.planId==="install"?"registry_only":"none"})}
export function defaultExecutionPlans(manager:PackageManager){return{install:{...createNamedPlan({planId:"install",manager,origin:"built_in",required:true}),timeoutMs:60_000},checks:["test","lint","typecheck"].map(planId=>({...createNamedPlan({planId:planId as "test"|"lint"|"typecheck",manager,origin:"built_in",required:planId==="test"}),timeoutMs:30_000}))}}
export function validatePlan(plan:CommandPlan){const expected=commands[plan.executable]?.[plan.planId];if(!expected||plan.args.length!==expected.length||plan.args.some((arg,index)=>arg!==expected[index])||plan.kind!==kinds[plan.planId])throw new Error("command_not_allowed");if(plan.origin!=="built_in"&&plan.origin!=="trusted_ref")throw new Error("untrusted_command_origin");if(plan.timeoutMs<1||plan.timeoutMs>1_200_000||plan.cpuLimit<1||plan.cpuLimit>4||plan.memoryMb<128||plan.memoryMb>8192||plan.outputBytes<1||plan.outputBytes>25_000_000||plan.fileBytes<1||plan.fileBytes>2_000_000_000)throw new Error("invalid_resource_limit");if((plan.planId==="install")!==(plan.network==="registry_only"))throw new Error("invalid_network_policy");return plan}
export type Workspace={files:Map<string,string>;environment:Record<string,string>;remote?:string;credentialHelper?:string;tokenRevoked:boolean};
export function teardownCredentials(workspace:Workspace){for(const key of Object.keys(workspace.environment))if(/TOKEN|KEY|SECRET|PASSWORD|CREDENTIAL/i.test(key))delete workspace.environment[key];delete workspace.remote;delete workspace.credentialHelper;workspace.tokenRevoked=true;return workspace}
export function executionReady(workspace:Workspace){return workspace.tokenRevoked&&!workspace.remote&&!workspace.credentialHelper&&!Object.keys(workspace.environment).some(k=>/TOKEN|KEY|SECRET|PASSWORD|CREDENTIAL/i.test(k))}
export function finalStatus(results:CheckResult[]){const required=results.filter(r=>r.required);if(required.some(r=>r.conclusion==="not_run"||r.conclusion==="timed_out"||r.conclusion==="truncated"))return "inconclusive" as const;if(required.some(r=>r.conclusion==="failed"))return "changes_requested" as const;return "checks_passed" as const}
export type ComparableCheck={commitSha:string;commandFingerprint:string;configRevision:string;runnerImage:string;toolVersions:string;architecture:string;networkPolicy:string;conclusion:"passed"|"failed"|"flaky"|"not_run"|"timed_out"|"truncated"};
export function classifyRegression(base:ComparableCheck,head:ComparableCheck){for(const field of ["commandFingerprint","configRevision","runnerImage","toolVersions","architecture","networkPolicy"] as const)if(base[field]!==head[field])return{classification:"unknown" as const,reason:`configuration_mismatch:${field}`};if(base.commitSha===head.commitSha)return{classification:"unknown" as const,reason:"same_commit"};if(base.conclusion==="flaky"||head.conclusion==="flaky")return{classification:"flaky" as const};if(!["passed","failed"].includes(base.conclusion)||!["passed","failed"].includes(head.conclusion))return{classification:"unknown" as const,reason:"incomplete_evidence"};if(base.conclusion==="passed"&&head.conclusion==="failed")return{classification:"introduced" as const};if(base.conclusion==="failed"&&head.conclusion==="failed")return{classification:"pre_existing" as const};if(base.conclusion==="failed"&&head.conclusion==="passed")return{classification:"resolved" as const};return{classification:"unchanged_pass" as const}}
export type DiagnosticRun={conclusion:"passed"|"failed";failureFingerprint?:string};
export function diagnoseFlakiness(runs:DiagnosticRun[],maxRuns=3){if(!Number.isInteger(maxRuns)||maxRuns<2||maxRuns>5)throw new Error("invalid_flaky_rerun_limit");if(runs.length<2)return{classification:"insufficient" as const,nextRunAllowed:runs.length<maxRuns};if(runs.length>maxRuns)throw new Error("flaky_rerun_limit_exceeded");const outcomes=new Set(runs.map(run=>run.conclusion)),failureFingerprints=new Set(runs.filter(run=>run.conclusion==="failed").map(run=>run.failureFingerprint??"missing"));if(outcomes.size>1)return{classification:"flaky" as const,nextRunAllowed:false,fingerprintStable:failureFingerprints.size<=1};if(outcomes.has("passed"))return{classification:"stable_pass" as const,nextRunAllowed:false};if(failureFingerprints.size===1&&!failureFingerprints.has("missing"))return{classification:"stable_failure" as const,nextRunAllowed:false,failureFingerprint:[...failureFingerprints][0]!};return{classification:"unknown_failure" as const,nextRunAllowed:runs.length<maxRuns}}
export async function runFlakyDiagnostics(initial:DiagnosticRun,rerun:()=>Promise<DiagnosticRun>,maxRuns=3){const runs=[initial];if(initial.conclusion==="passed")return{runs,diagnosis:{classification:"stable_pass" as const,nextRunAllowed:false}};while(runs.length<maxRuns){runs.push(await rerun());const diagnosis=diagnoseFlakiness(runs,maxRuns);if(!diagnosis.nextRunAllowed)return{runs,diagnosis}}return{runs,diagnosis:diagnoseFlakiness(runs,maxRuns)}}
export * from "./vercelSandbox.js";
