export type RiskClass = "low" | "medium" | "high" | "critical";
export type DefectFamily = "requirement_mismatch" | "logic_edge_case" | "regression" | "authorization_tenant" | "injection_taint" | "dependency_cve" | "secret" | "concurrency" | "error_handling" | "performance_resource" | "configuration_architecture" | "missing_tests";
export type LabeledFinding = { caseId: string; language: string; risk: RiskClass; defectFamily: DefectFamily; expected: boolean; surfaced: boolean; expectedSeverity?: RiskClass; predictedSeverity?: RiskClass; evidenceSupported: boolean; repeatGroup: string; repetition: number };
export type PatchResult = { caseId: string; language: string; risk: RiskClass; proposed: boolean; appliedCleanly: boolean; requiredChecksPassed: boolean; introducedRegression: boolean; humanAccepted?: boolean };
export type EvaluationRun = { setVersion: string; promptVersion: string; findings: LabeledFinding[]; patches: PatchResult[]; latencyMs: number[]; costUsd: number[] };
export type AccuracyThresholds = { minimumCases: number; minimumLanguages: number; requiredLanguages: string[]; minimumNegativeCases: number; minimumPatchCases: number; minimumRepetitionsPerCase: number; minimumCasesPerLanguage: number; minimumPositiveCasesPerLanguage: number; minimumNegativeCasesPerLanguage: number; minimumCasesPerRisk: number; minimumPositiveCasesPerRisk: number; minimumNegativeCasesPerRisk: number; requiredRisks: RiskClass[]; requiredDefectFamilies: DefectFamily[]; minimumCasesPerDefectFamily: number; minimumPositiveCasesPerDefectFamily: number; minimumNegativeCasesPerDefectFamily: number; precision: number; recall: number; criticalRecall: number; severityAccuracy: number; maximumUnsupportedClaimRate: number; stability: number; repeatedCaseCoverage: number; patchApplyRate: number; patchPassRate: number; maximumPatchRegressionRate: number; maximumP95LatencyMs: number; maximumP95CostUsd: number };
export const releaseThresholds: AccuracyThresholds = { minimumCases: 50, minimumLanguages: 3, requiredLanguages: ["typescript", "python", "java"], minimumNegativeCases: 15, minimumPatchCases: 20, minimumRepetitionsPerCase: 3, minimumCasesPerLanguage: 10, minimumPositiveCasesPerLanguage: 5, minimumNegativeCasesPerLanguage: 3, minimumCasesPerRisk: 3, minimumPositiveCasesPerRisk: 3, minimumNegativeCasesPerRisk: 1, requiredRisks: ["high", "critical"], requiredDefectFamilies: ["requirement_mismatch", "logic_edge_case", "regression", "authorization_tenant", "injection_taint", "dependency_cve", "secret", "concurrency", "error_handling", "performance_resource", "configuration_architecture", "missing_tests"], minimumCasesPerDefectFamily: 2, minimumPositiveCasesPerDefectFamily: 1, minimumNegativeCasesPerDefectFamily: 1, precision: .85, recall: .8, criticalRecall: .9, severityAccuracy: .8, maximumUnsupportedClaimRate: .02, stability: .9, repeatedCaseCoverage: 1, patchApplyRate: .9, patchPassRate: .8, maximumPatchRegressionRate: .02, maximumP95LatencyMs: 15 * 60_000, maximumP95CostUsd: 5 };
const ratio = (top: number, bottom: number, empty = 1) => bottom ? top / bottom : empty;
const p95 = (values: number[]) => { if (!values.length) return Number.POSITIVE_INFINITY; const sorted = [...values].sort((a, b) => a - b); return sorted[Math.ceil(sorted.length * .95) - 1]!; };
const uniqueCases = (rows: LabeledFinding[]) => new Set(rows.map(row => row.caseId));
export function evaluationIntegrityFailures(run: EvaluationRun, expectedRepetitions = releaseThresholds.minimumRepetitionsPerCase) {
  const failures = new Set<string>(), seen = new Set<string>(), groups = new Map<string, LabeledFinding[]>(), caseGroups = new Map<string, Set<string>>();
  for (const row of run.findings) { if (!row.caseId || !row.repeatGroup || !row.language || !Number.isSafeInteger(row.repetition) || row.repetition < 0) failures.add("finding_identity_invalid"); const repetitionKey = `${row.repeatGroup}:${row.repetition}`; if (seen.has(repetitionKey)) failures.add("duplicate_repetition"); seen.add(repetitionKey); groups.set(row.repeatGroup, [...(groups.get(row.repeatGroup) ?? []), row]); caseGroups.set(row.caseId, new Set([...(caseGroups.get(row.caseId) ?? []), row.repeatGroup])); }
  if ([...caseGroups.values()].some(values => values.size !== 1)) failures.add("case_repeat_group_inconsistent");
  for (const rows of groups.values()) { const first = rows[0]!; if (rows.some(row => row.caseId !== first.caseId || row.language !== first.language || row.risk !== first.risk || row.defectFamily !== first.defectFamily || row.expected !== first.expected || row.expectedSeverity !== first.expectedSeverity)) failures.add("repeat_label_inconsistent"); const sequence = rows.map(row => row.repetition).sort((a, b) => a - b); if (sequence.length !== expectedRepetitions || sequence.some((value, index) => value !== index)) failures.add("repetition_sequence_invalid"); }
  if ([...run.latencyMs, ...run.costUsd].some(value => !Number.isFinite(value) || value < 0)) failures.add("measurement_invalid"); return [...failures].sort();
}
function findingScore(rows: LabeledFinding[], minimumRepetitionsPerCase: number) {
  const surfaced = rows.filter(row => row.surfaced), truePositive = surfaced.filter(row => row.expected), expected = rows.filter(row => row.expected), severities = truePositive.filter(row => row.expectedSeverity), unsupported = surfaced.filter(row => !row.evidenceSupported), repeatGroups = new Map<string, LabeledFinding[]>();
  for (const row of rows) repeatGroups.set(row.repeatGroup, [...(repeatGroups.get(row.repeatGroup) ?? []), row]);
  const repeatedGroups = [...repeatGroups.values()].filter(group => group.length >= minimumRepetitionsPerCase), stableGroups = repeatedGroups.filter(group => group.every(row => row.surfaced === group[0]!.surfaced && row.predictedSeverity === group[0]!.predictedSeverity));
  return { caseCount: uniqueCases(rows).size, positiveCaseCount: uniqueCases(rows.filter(row => row.expected)).size, negativeCaseCount: uniqueCases(rows.filter(row => !row.expected)).size, precision: ratio(truePositive.length, surfaced.length), recall: ratio(truePositive.length, expected.length, 0), severityAccuracy: ratio(severities.filter(row => row.expectedSeverity === row.predictedSeverity).length, severities.length, 0), unsupportedClaimRate: ratio(unsupported.length, surfaced.length), stability: ratio(stableGroups.length, repeatedGroups.length, 0) };
}
export function score(run: EvaluationRun, minimumRepetitionsPerCase = releaseThresholds.minimumRepetitionsPerCase) {
  const finding = findingScore(run.findings, minimumRepetitionsPerCase), expected = run.findings.filter(row => row.expected), critical = expected.filter(row => row.expectedSeverity === "critical"), proposed = run.patches.filter(row => row.proposed), applied = proposed.filter(row => row.appliedCleanly), groups = new Map<string, number>();
  for (const row of run.findings) groups.set(row.repeatGroup, (groups.get(row.repeatGroup) ?? 0) + 1);
  const repeatedGroupCount = [...groups.values()].filter(count => count >= minimumRepetitionsPerCase).length;
  return { caseCount: new Set([...run.findings.map(row => row.caseId), ...run.patches.map(row => row.caseId)]).size, languageCount: new Set([...run.findings.map(row => row.language), ...run.patches.map(row => row.language)]).size, negativeCaseCount: finding.negativeCaseCount, patchCaseCount: new Set(run.patches.map(row => row.caseId)).size, repeatedCaseCoverage: ratio(repeatedGroupCount, uniqueCases(run.findings).size, 0), precision: finding.precision, recall: finding.recall, criticalRecall: ratio(critical.filter(row => row.surfaced).length, critical.length, 0), severityAccuracy: finding.severityAccuracy, unsupportedClaimRate: finding.unsupportedClaimRate, stability: finding.stability, patchApplyRate: ratio(applied.length, proposed.length, 0), patchPassRate: ratio(applied.filter(row => row.requiredChecksPassed).length, applied.length, 0), patchRegressionRate: ratio(proposed.filter(row => row.introducedRegression).length, proposed.length), p95LatencyMs: p95(run.latencyMs), p95CostUsd: p95(run.costUsd) };
}
function sliceFailures(name: string, rows: LabeledFinding[], thresholds: AccuracyThresholds, minimumCases: number, minimumPositiveCases: number, minimumNegativeCases: number) {
  const value = findingScore(rows, thresholds.minimumRepetitionsPerCase), failures: string[] = [];
  if (value.caseCount < minimumCases) failures.push(`${name}_caseCount_below_threshold`); if (value.positiveCaseCount < minimumPositiveCases) failures.push(`${name}_positiveCaseCount_below_threshold`); if (value.negativeCaseCount < minimumNegativeCases) failures.push(`${name}_negativeCaseCount_below_threshold`); if (value.precision < thresholds.precision) failures.push(`${name}_precision_below_threshold`); if (value.recall < thresholds.recall) failures.push(`${name}_recall_below_threshold`); if (value.severityAccuracy < thresholds.severityAccuracy) failures.push(`${name}_severityAccuracy_below_threshold`); if (value.unsupportedClaimRate > thresholds.maximumUnsupportedClaimRate) failures.push(`${name}_unsupportedClaimRate_above_threshold`); if (value.stability < thresholds.stability) failures.push(`${name}_stability_below_threshold`); return failures;
}
export function releaseGate(run: EvaluationRun, thresholds = releaseThresholds) {
  const value = score(run, thresholds.minimumRepetitionsPerCase), failures: string[] = evaluationIntegrityFailures(run, thresholds.minimumRepetitionsPerCase);
  const minimums: Array<[keyof typeof value, number]> = [["caseCount", thresholds.minimumCases], ["languageCount", thresholds.minimumLanguages], ["negativeCaseCount", thresholds.minimumNegativeCases], ["patchCaseCount", thresholds.minimumPatchCases], ["repeatedCaseCoverage", thresholds.repeatedCaseCoverage], ["precision", thresholds.precision], ["recall", thresholds.recall], ["criticalRecall", thresholds.criticalRecall], ["severityAccuracy", thresholds.severityAccuracy], ["stability", thresholds.stability], ["patchApplyRate", thresholds.patchApplyRate], ["patchPassRate", thresholds.patchPassRate]]; for (const [key, limit] of minimums) if (value[key] < limit) failures.push(`${key}_below_threshold`);
  const maximums: Array<[keyof typeof value, number]> = [["unsupportedClaimRate", thresholds.maximumUnsupportedClaimRate], ["patchRegressionRate", thresholds.maximumPatchRegressionRate], ["p95LatencyMs", thresholds.maximumP95LatencyMs], ["p95CostUsd", thresholds.maximumP95CostUsd]]; for (const [key, limit] of maximums) if (value[key] > limit) failures.push(`${key}_above_threshold`);
  for (const language of thresholds.requiredLanguages) failures.push(...sliceFailures(`language_${language}`, run.findings.filter(row => row.language === language), thresholds, thresholds.minimumCasesPerLanguage, thresholds.minimumPositiveCasesPerLanguage, thresholds.minimumNegativeCasesPerLanguage));
  for (const risk of thresholds.requiredRisks) failures.push(...sliceFailures(`risk_${risk}`, run.findings.filter(row => row.risk === risk), thresholds, thresholds.minimumCasesPerRisk, thresholds.minimumPositiveCasesPerRisk, thresholds.minimumNegativeCasesPerRisk));
  for (const family of thresholds.requiredDefectFamilies) failures.push(...sliceFailures(`family_${family}`, run.findings.filter(row => row.defectFamily === family), thresholds, thresholds.minimumCasesPerDefectFamily, thresholds.minimumPositiveCasesPerDefectFamily, thresholds.minimumNegativeCasesPerDefectFamily));
  return { passed: failures.length === 0, failures: [...new Set(failures)], score: value, setVersion: run.setVersion, promptVersion: run.promptVersion };
}
