export type RiskClass = "low" | "medium" | "high" | "critical";
export type LabeledFinding = { caseId: string; language: string; risk: RiskClass; expected: boolean; surfaced: boolean; expectedSeverity?: RiskClass; predictedSeverity?: RiskClass; evidenceSupported: boolean; repeatGroup: string };
export type PatchResult = { caseId: string; language: string; risk: RiskClass; proposed: boolean; appliedCleanly: boolean; requiredChecksPassed: boolean; introducedRegression: boolean; humanAccepted?: boolean };
export type EvaluationRun = { setVersion: string; promptVersion: string; findings: LabeledFinding[]; patches: PatchResult[]; latencyMs: number[]; costUsd: number[] };
export type AccuracyThresholds = { minimumCases: number; minimumLanguages: number; precision: number; recall: number; criticalRecall: number; severityAccuracy: number; maximumUnsupportedClaimRate: number; stability: number; patchApplyRate: number; patchPassRate: number; maximumPatchRegressionRate: number; maximumP95LatencyMs: number; maximumP95CostUsd: number };
export const releaseThresholds: AccuracyThresholds = { minimumCases: 50, minimumLanguages: 3, precision: .85, recall: .8, criticalRecall: .9, severityAccuracy: .8, maximumUnsupportedClaimRate: .02, stability: .9, patchApplyRate: .9, patchPassRate: .8, maximumPatchRegressionRate: .02, maximumP95LatencyMs: 15 * 60_000, maximumP95CostUsd: 5 };
const ratio = (top: number, bottom: number, empty = 1) => bottom ? top / bottom : empty;
const p95 = (values: number[]) => { if (!values.length) return Number.POSITIVE_INFINITY; const sorted = [...values].sort((a, b) => a - b); return sorted[Math.ceil(sorted.length * .95) - 1]!; };
export function score(run: EvaluationRun) {
  const surfaced = run.findings.filter(row => row.surfaced), truePositive = surfaced.filter(row => row.expected), expected = run.findings.filter(row => row.expected), critical = expected.filter(row => row.expectedSeverity === "critical"), severities = truePositive.filter(row => row.expectedSeverity && row.predictedSeverity), unsupported = surfaced.filter(row => !row.evidenceSupported), proposed = run.patches.filter(row => row.proposed), applied = proposed.filter(row => row.appliedCleanly), repeatGroups = new Map<string, LabeledFinding[]>();
  for (const row of run.findings) repeatGroups.set(row.repeatGroup, [...(repeatGroups.get(row.repeatGroup) ?? []), row]);
  const stableGroups = [...repeatGroups.values()].filter(rows => rows.every(row => row.surfaced === rows[0]!.surfaced && row.predictedSeverity === rows[0]!.predictedSeverity));
  return { caseCount: new Set([...run.findings.map(row => row.caseId), ...run.patches.map(row => row.caseId)]).size, languageCount: new Set([...run.findings.map(row => row.language), ...run.patches.map(row => row.language)]).size, precision: ratio(truePositive.length, surfaced.length), recall: ratio(truePositive.length, expected.length), criticalRecall: ratio(critical.filter(row => row.surfaced).length, critical.length, 0), severityAccuracy: ratio(severities.filter(row => row.expectedSeverity === row.predictedSeverity).length, severities.length, 0), unsupportedClaimRate: ratio(unsupported.length, surfaced.length), stability: ratio(stableGroups.length, repeatGroups.size, 0), patchApplyRate: ratio(applied.length, proposed.length, 0), patchPassRate: ratio(applied.filter(row => row.requiredChecksPassed).length, applied.length, 0), patchRegressionRate: ratio(proposed.filter(row => row.introducedRegression).length, proposed.length), p95LatencyMs: p95(run.latencyMs), p95CostUsd: p95(run.costUsd) };
}
export function releaseGate(run: EvaluationRun, thresholds = releaseThresholds) { const value = score(run), failures: string[] = [];
  const minimums: Array<[keyof typeof value, number]> = [["caseCount", thresholds.minimumCases], ["languageCount", thresholds.minimumLanguages], ["precision", thresholds.precision], ["recall", thresholds.recall], ["criticalRecall", thresholds.criticalRecall], ["severityAccuracy", thresholds.severityAccuracy], ["stability", thresholds.stability], ["patchApplyRate", thresholds.patchApplyRate], ["patchPassRate", thresholds.patchPassRate]];
  for (const [key, limit] of minimums) if (value[key] < limit) failures.push(`${key}_below_threshold`);
  const maximums: Array<[keyof typeof value, number]> = [["unsupportedClaimRate", thresholds.maximumUnsupportedClaimRate], ["patchRegressionRate", thresholds.maximumPatchRegressionRate], ["p95LatencyMs", thresholds.maximumP95LatencyMs], ["p95CostUsd", thresholds.maximumP95CostUsd]];
  for (const [key, limit] of maximums) if (value[key] > limit) failures.push(`${key}_above_threshold`);
  return { passed: failures.length === 0, failures, score: value, setVersion: run.setVersion, promptVersion: run.promptVersion };
}
