export default async function Review({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  return <div className="content review-detail">
    <div className="crumbs"><a href="/reviews?tour=1">Review queue</a><span>›</span><strong>nexus/api #{id}</strong><span className="sample-badge">Sample evidence</span></div>
    <section className="verdict-card"><div><span className="status danger">Changes requested</span><h1>One requirement is unsupported</h1><p>The required test suite also fails at the exact reviewed commit. No fix candidate was delivered.</p></div><div className="verdict-actions"><button className="button secondary" type="button" disabled>Re-run after repository connection</button><a className="button" href="/setup/install">Connect repository</a></div></section>
    <section className="commit-strip" aria-label="Pinned review context"><span><small>Repository</small><strong>nexus/api</strong></span><span><small>Pull request</small><strong>#{id}</strong></span><span><small>Head commit</small><code>a3f91c2</code></span><span><small>Base commit</small><code>7b2e004</code></span><span><small>Configuration</small><code>main @ 7b2e004</code></span><span><small>Coverage</small><strong>Partial</strong></span></section>
    <div className="next-action"><span className="next-mark">!</span><div><strong>Next action: human decision</strong><p>Ask the author to cover criterion 3, or connect this repository to run a fresh evidence-backed review.</p></div></div>
    <section className="evidence-section"><div className="evidence-heading"><div><p className="eyebrow">Requirements</p><h2>Criteria coverage</h2></div><span>4 criteria · 3 evaluated</span></div><div className="evidence-table"><div className="evidence-row evidence-header"><span>#</span><span>Acceptance criterion</span><span>Verdict</span><span>Evidence</span></div><Criterion number="1" criterion="Reject transfers above daily limit" verdict="Covered" tone="success" evidence="src/limits/daily.ts:44" /><Criterion number="2" criterion="Return 429 with retry-after" verdict="Covered" tone="success" evidence="src/http/rate.ts:112" /><Criterion number="3" criterion="Log every rejected transfer" verdict="Not covered" tone="danger" evidence="No matching change found in searched scope" /><Criterion number="4" criterion="Existing partner integrations keep working" verdict="Unclear" tone="warning" evidence="src/partners/adapter.ts:88" /></div><footer className="evidence-foot">Every verdict cites pinned evidence, or BuildIT does not publish it.</footer></section>
    <section className="evidence-section"><div className="evidence-heading"><div><p className="eyebrow">Deterministic checks</p><h2>Validation matrix</h2></div><span>1 required · 2 not configured</span></div><div className="validation-table"><div className="validation-row evidence-header"><span>Check</span><span>Policy</span><span>Result</span><span>Duration</span><span>Artifact</span></div><Check name="pnpm test" policy="Required" result="Failed" tone="danger" duration="1m 42s" artifact="View sample log" /><Check name="pnpm lint" policy="Optional" result="Not run" tone="neutral" duration="—" artifact="—" /><Check name="pnpm typecheck" policy="Optional" result="Not run" tone="neutral" duration="—" artifact="—" /></div><footer className="evidence-foot">Not checked: build, dependency audit, secret scan. This review cannot claim repository-wide validation.</footer></section>
  </div>;
}

function Criterion({ number, criterion, verdict, tone, evidence }: { number: string; criterion: string; verdict: string; tone: string; evidence: string }) { return <div className="evidence-row"><code>{number}</code><strong>{criterion}</strong><span className={`status ${tone}`}>{verdict}</span><code>{evidence}</code></div>; }
function Check({ name, policy, result, tone, duration, artifact }: { name: string; policy: string; result: string; tone: string; duration: string; artifact: string }) { return <div className="validation-row"><code>{name}</code><span>{policy}</span><span className={`status ${tone}`}>{result}</span><time>{duration}</time><a href="#sample-log">{artifact}</a></div>; }
