import {createHmac,generateKeyPairSync} from "node:crypto";
import {describe,expect,it,vi} from "vitest";
import {authorizeTrigger,canCommitSensitiveWrite,deliverStackedPr,DeliveryLedger,GitHubAppClient,pinPullRequest,PushDebouncer,reviewPolicy,sideEffectKey,trustedConfiguration,verifyWebhook} from "../src/index.js";
describe("GitHub boundary",()=>{
 it("verifies raw webhook bytes",()=>{const body=Buffer.from('{"x":1}'),sig="sha256="+createHmac("sha256","s").update(body).digest("hex");expect(verifyWebhook(body,sig,"s")).toBe(true);expect(verifyWebhook(Buffer.from("changed"),sig,"s")).toBe(false)});
 it("deduplicates deliveries",()=>{const l=new DeliveryLedger();expect(l.accept("d")).toBe(true);expect(l.accept("d")).toBe(false)});
 it("rejects bots, edits, and weak autofix actors",()=>{expect(authorizeTrigger({deliveryId:"1",action:"created",senderType:"Bot",body:"@buildit review",permission:"admin"}).accepted).toBe(false);expect(authorizeTrigger({deliveryId:"2",action:"created",senderType:"User",body:"@buildit autofix",permission:"triage"}).accepted).toBe(false)});
 it("never trusts head configuration",()=>expect(()=>trustedConfiguration({defaultBranch:"main",headSha:"a",trustedSha:"a",protectionVerified:true,explicitlyApproved:false})).toThrow());
 it("guards commit-sensitive writes",()=>expect(canCommitSensitiveWrite("a","b")).toBe(false));
 it("pins exact head and base commits and refuses merge queues",()=>{const snapshot=pinPullRequest({number:7,head:{sha:"a".repeat(40),ref:"gh-readonly-queue/main/pr-7",repoFullName:"owner/repo"},base:{sha:"b".repeat(40),ref:"main",repoFullName:"owner/repo"}});expect(snapshot).toMatchObject({headSha:"a".repeat(40),baseSha:"b".repeat(40),fromMergeQueue:true});expect(reviewPolicy(snapshot,"review","manual_review_only")).toEqual({allowed:false,reason:"merge_queue_refused"})});
 it("allows read-only fork review but never fork autofix",()=>{const snapshot=pinPullRequest({number:8,head:{sha:"a".repeat(40),ref:"feature",repoFullName:"contributor/fork"},base:{sha:"b".repeat(40),ref:"main",repoFullName:"owner/repo"}});expect(reviewPolicy(snapshot,"review","manual_review_only")).toEqual({allowed:true});expect(reviewPolicy(snapshot,"autofix","manual_review_only")).toEqual({allowed:false,reason:"fork_manual_review_only"})});
 it("debounces pushes by repository and PR head",()=>{const debounce=new PushDebouncer();debounce.schedule("repo:7","a",100,50);debounce.schedule("repo:7","b",120,50);expect(debounce.claim("repo:7","a",200)).toBe(false);expect(debounce.claim("repo:7","b",169)).toBe(false);expect(debounce.claim("repo:7","b",170)).toBe(true)});
 it("builds commit-bound idempotency keys",()=>expect(sideEffectKey({repositoryId:1,prNumber:7,headSha:"a".repeat(40),kind:"comment"})).toBe(`1:7:${"a".repeat(40)}:comment:primary`));
 it("delivers only a fully validated stacked PR",async()=>{const calls:string[]=[];const client={createBranch:async()=>{calls.push("branch")},createPullRequest:async(input:{base:string})=>{calls.push(input.base);return{number:2,url:"https://example/pr/2"}}};await expect(deliverStackedPr(client,{jobId:"j",prNumber:1,sourceBranch:"feature",pinnedHead:"a",currentHead:"a",candidateSha:"b",allRequiredChecksPassed:true})).resolves.toMatchObject({number:2});expect(calls).toEqual(["branch","feature"]);await expect(deliverStackedPr(client,{jobId:"j",prNumber:1,sourceBranch:"feature",pinnedHead:"a",currentHead:"c",candidateSha:"b",allRequiredChecksPassed:true})).rejects.toThrow("stale_head")});
});

describe("GitHub App tokens",()=>{
 const privateKey=generateKeyPairSync("rsa",{modulusLength:2048}).privateKey.export({type:"pkcs8",format:"pem"}).toString();
 it("mints and caches a review token for exactly one repository",async()=>{const requests:Array<{body:unknown}>=[];const http=vi.fn(async(_url:string|URL,init?:RequestInit)=>{requests.push({body:JSON.parse(String(init?.body))});return new Response(JSON.stringify({token:"installation-token",expires_at:"2030-01-01T00:00:00Z"}),{status:201})});const client=new GitHubAppClient({appId:"1",privateKey,http,now:()=>1_700_000_000_000});expect(await client.tokenFor({installationId:22,repositoryId:33,stage:"review"})).toBe("installation-token");expect(await client.tokenFor({installationId:22,repositoryId:33,stage:"review"})).toBe("installation-token");expect(http).toHaveBeenCalledTimes(1);expect(requests[0]?.body).toEqual({repository_ids:[33],permissions:{metadata:"read",contents:"read",pull_requests:"write",issues:"read",checks:"write"}})});
 it("uses a separate write token for delivery and remints once after 401",async()=>{let mint=0;const http=vi.fn(async(_url:string|URL,init?:RequestInit)=>{const body=init?.body?JSON.parse(String(init.body)):undefined;if(body?.repository_ids)return new Response(JSON.stringify({token:`token-${++mint}`,expires_at:"2030-01-01T00:00:00Z"}),{status:201});return new Response("",{status:500})});const client=new GitHubAppClient({appId:"1",privateKey,http,now:()=>1_700_000_000_000});const operation=vi.fn(async(token:string)=>new Response("",{status:token==="token-1"?401:200}));const response=await client.withToken({installationId:22,repositoryId:33,stage:"autofix_delivery"},operation);expect(response.status).toBe(200);expect(operation).toHaveBeenNthCalledWith(1,"token-1");expect(operation).toHaveBeenNthCalledWith(2,"token-2")});
 it("rejects suspended installations and removed repositories",async()=>{const suspended=new GitHubAppClient({appId:"1",privateKey,http:vi.fn(async()=>new Response(JSON.stringify({suspended_at:"2026-01-01"}),{status:200}))});await expect(suspended.assertInstallation(22)).rejects.toThrow("installation_suspended");const removed=new GitHubAppClient({appId:"1",privateKey,http:vi.fn(async()=>new Response(JSON.stringify({message:"Not Found"}),{status:404}))});await expect(removed.repository({installationToken:"token",repositoryId:33})).rejects.toThrow("repository_unavailable")});
});
