import{describe,expect,it,vi}from"vitest";import{JiraContextClient,LinearContextClient}from"../src/tracker-context.js";
describe("tracker context",()=>{it("fetches an exact-version Linear issue inside the bound workspace",async()=>{const http=vi.fn(async()=>Response.json({data:{issue:{identifier:"ENG-4",title:"Limit transfers",description:"## Acceptance criteria\n- Reject excess",updatedAt:"2026-08-30T00:00:00Z",url:"https://linear.app/acme/issue/ENG-4/x"}}}));await expect(new LinearContextClient(http).fetch({token:"secret",workspaceSlug:"acme",url:"https://linear.app/acme/issue/ENG-4/x"})).resolves.toMatchObject({status:"available",version:"2026-08-30T00:00:00Z",content:expect.stringContaining("Reject excess")});expect(http).toHaveBeenCalledOnce()});it("rejects cross-workspace Linear URLs and reports forbidden, image-only, and oversized content",async()=>{await expect(new LinearContextClient().fetch({token:"x",workspaceSlug:"acme",url:"https://linear.app/other/issue/ENG-4/x"})).rejects.toThrow("linear_scope_mismatch");await expect(new LinearContextClient(async()=>new Response("",{status:403})).fetch({token:"x",workspaceSlug:"acme",url:"https://linear.app/acme/issue/ENG-4/x"})).resolves.toMatchObject({status:"inaccessible"});await expect(new LinearContextClient(async()=>Response.json({data:{issue:{identifier:"ENG-4",title:"Image",description:"![](x.png)",updatedAt:"v1",url:"https://linear.app/acme/issue/ENG-4/x"}}})).fetch({token:"x",workspaceSlug:"acme",url:"https://linear.app/acme/issue/ENG-4/x"})).resolves.toMatchObject({status:"image_only"});await expect(new LinearContextClient(async()=>Response.json({data:{issue:{identifier:"ENG-4",title:"Long",description:"x".repeat(20),updatedAt:"v1",url:"https://linear.app/acme/issue/ENG-4/x"}}})).fetch({token:"x",workspaceSlug:"acme",url:"https://linear.app/acme/issue/ENG-4/x",maxBytes:5})).resolves.toMatchObject({status:"oversized"})});it("fetches Jira ADF only from the bound site and handles missing or malformed issues",async()=>{const client=new JiraContextClient(async()=>Response.json({key:"API-7",fields:{summary:"Audit",updated:"v7",description:{type:"doc",content:[{type:"paragraph",content:[{type:"text",text:"Keep logs"}]}]}}}));await expect(client.fetch({token:"x",siteHost:"acme.atlassian.net",url:"https://acme.atlassian.net/browse/API-7"})).resolves.toMatchObject({status:"available",version:"v7",content:expect.stringContaining("Keep logs")});await expect(client.fetch({token:"x",siteHost:"acme.atlassian.net",url:"https://other.atlassian.net/browse/API-7"})).rejects.toThrow("jira_scope_mismatch");await expect(new JiraContextClient(async()=>new Response("",{status:404})).fetch({token:"x",siteHost:"acme.atlassian.net",url:"https://acme.atlassian.net/browse/API-7"})).resolves.toMatchObject({status:"missing"});await expect(new JiraContextClient(async()=>Response.json({fields:{}})).fetch({token:"x",siteHost:"acme.atlassian.net",url:"https://acme.atlassian.net/browse/API-7"})).rejects.toThrow("jira_issue_malformed")})});

it("uses the Jira OAuth cloud endpoint and rejects an unselected project before fetching", async () => {
  const http = vi.fn(async (_input: string | URL, _init?: RequestInit) => Response.json({ key: "ENG-4", fields: { summary: "Title", description: null, updated: "v1" } }));
  const client = new JiraContextClient(http);
  await expect(client.fetch({ token: "oauth-access", url: "https://acme.atlassian.net/browse/OTHER-4", siteHost: "acme.atlassian.net", cloudId: "cloud-one", projectKeys: ["ENG"] })).rejects.toThrow("jira_scope_mismatch");
  expect(http).not.toHaveBeenCalled();
  await client.fetch({ token: "oauth-access", url: "https://acme.atlassian.net/browse/ENG-4", siteHost: "acme.atlassian.net", cloudId: "cloud-one", projectKeys: ["ENG"] });
  expect(String(http.mock.calls[0]?.[0])).toContain("https://api.atlassian.com/ex/jira/cloud-one/rest/api/3/issue/ENG-4");
});
