import { describe, expect, it, vi } from "vitest";
import { ProviderClient, ProviderError } from "../src/index.js";
const request={model:"allowed",system:"policy",input:"data",schemaName:"result",schema:{type:"object",properties:{ok:{type:"boolean"}},required:["ok"],additionalProperties:false},maxOutputTokens:100};
describe("provider adapters",()=>{
  it("validates Gemini keys in a header, never a URL",async()=>{const http=vi.fn(async(input:string|URL,init?:RequestInit)=>{expect(String(input)).not.toContain("secret-key-value");expect(new Headers(init?.headers).get("x-goog-api-key")).toBe("secret-key-value");return new Response(JSON.stringify({models:[]}))});expect(await new ProviderClient(http).validateKey("gemini","secret-key-value")).toBe(true)});
  it("normalizes Anthropic tool output",async()=>{const http=vi.fn(async()=>new Response(JSON.stringify({stop_reason:"tool_use",content:[{type:"tool_use",name:"result",input:{ok:true}}],usage:{input_tokens:4,output_tokens:2}})));await expect(new ProviderClient(http).generate("anthropic","key",request,new Set(["allowed"]))).resolves.toMatchObject({value:{ok:true},inputTokens:4,outputTokens:2})});
  it("normalizes OpenAI structured output",async()=>{const http=vi.fn(async()=>new Response(JSON.stringify({status:"completed",output:[{type:"message",content:[{type:"output_text",text:"{\"ok\":true}"}]}],usage:{input_tokens:3,output_tokens:1}})));await expect(new ProviderClient(http).generate("openai","key",request,new Set(["allowed"]))).resolves.toMatchObject({value:{ok:true},finishReason:"completed"})});
  it("normalizes Gemini structured output",async()=>{const http=vi.fn(async(_url:string|URL,init?:RequestInit)=>{const body=JSON.parse(String(init?.body));expect(body.generationConfig.responseSchema).toEqual(request.schema);return new Response(JSON.stringify({candidates:[{finishReason:"STOP",content:{parts:[{text:"{\"ok\":true}"}]}}],usageMetadata:{promptTokenCount:3,candidatesTokenCount:1}}))});await expect(new ProviderClient(http).generate("gemini","key",request,new Set(["allowed"]))).resolves.toMatchObject({value:{ok:true},finishReason:"STOP"})});
  it("uses sanitized provider errors",async()=>{const client=new ProviderClient(async()=>new Response(JSON.stringify({error:{message:"secret leaked upstream"}}),{status:401}));await expect(client.validateKey("gemini","secret-key-value")).rejects.toEqual(expect.objectContaining({message:"invalid_key"}));await expect(client.validateKey("gemini","short")).rejects.toBeInstanceOf(ProviderError)});
});
