import { describe, expect, it, vi } from "vitest";
import { assertStrictSchema, ProviderClient, ProviderError } from "../src/index.js";
const request={model:"allowed",system:"policy",input:"data",schemaName:"result",schema:{type:"object",properties:{ok:{type:"boolean"}},required:["ok"],additionalProperties:false},maxOutputTokens:100};
describe("provider adapters",()=>{
  it("validates Gemini keys in a header, never a URL, and records only supported models",async()=>{const http=vi.fn(async(input:string|URL,init?:RequestInit)=>{expect(String(input)).not.toContain("secret-key-value");expect(new Headers(init?.headers).get("x-goog-api-key")).toBe("secret-key-value");return new Response(JSON.stringify({models:[{name:"models/gemini-2.5-pro",supportedGenerationMethods:["generateContent"]},{name:"models/gemini-2.5-flash",supportedGenerationMethods:["embedContent"]},{name:"models/not-approved",supportedGenerationMethods:["generateContent"]}]}))});await expect(new ProviderClient(http).validateKey("gemini","secret-key-value")).resolves.toEqual({availableModels:["gemini-2.5-pro"]})});
  it("normalizes Anthropic tool output",async()=>{const http=vi.fn(async()=>new Response(JSON.stringify({stop_reason:"tool_use",content:[{type:"tool_use",name:"result",input:{ok:true}}],usage:{input_tokens:4,output_tokens:2}})));await expect(new ProviderClient(http).generate("anthropic","key",request,new Set(["allowed"]))).resolves.toMatchObject({value:{ok:true},inputTokens:4,outputTokens:2})});
  it("normalizes OpenAI structured output",async()=>{const http=vi.fn(async()=>new Response(JSON.stringify({status:"completed",output:[{type:"message",content:[{type:"output_text",text:"{\"ok\":true}"}]}],usage:{input_tokens:3,output_tokens:1}})));await expect(new ProviderClient(http).generate("openai","key",request,new Set(["allowed"]))).resolves.toMatchObject({value:{ok:true},finishReason:"completed"})});
  it("normalizes Gemini structured output",async()=>{const http=vi.fn(async(_url:string|URL,init?:RequestInit)=>{const body=JSON.parse(String(init?.body));expect(body.generationConfig.responseJsonSchema).toEqual(request.schema);expect(body.generationConfig.responseSchema).toBeUndefined();return new Response(JSON.stringify({candidates:[{finishReason:"STOP",content:{parts:[{text:"{\"ok\":true}"}]}}],usageMetadata:{promptTokenCount:3,candidatesTokenCount:1}}))});await expect(new ProviderClient(http).generate("gemini","key",request,new Set(["allowed"]))).resolves.toMatchObject({value:{ok:true},finishReason:"STOP"})});
  it("uses sanitized provider errors",async()=>{const client=new ProviderClient(async()=>new Response(JSON.stringify({error:{message:"secret leaked upstream"}}),{status:401}));await expect(client.validateKey("gemini","secret-key-value")).rejects.toEqual(expect.objectContaining({message:"invalid_key"}));await expect(client.validateKey("gemini","short")).rejects.toBeInstanceOf(ProviderError)});
  it("rejects non-strict input schemas but leaves parseable output validation to the bounded repair stage",async()=>{expect(()=>assertStrictSchema({type:"object",properties:{nested:{type:"object",properties:{}}},additionalProperties:false})).toThrow("malformed_response");const client=new ProviderClient(async()=>new Response(JSON.stringify({status:"completed",output:[{type:"message",content:[{type:"output_text",text:'{"ok":true,"extra":1}'}]}]})));await expect(client.generate("openai","key",request,new Set(["allowed"]))).resolves.toMatchObject({value:{ok:true,extra:1}})});
  it("retries only temporary 429 and 529 failures with bounded backoff",async()=>{let call=0;const waits:number[]=[];const client=new ProviderClient(async()=>++call===1?new Response("",{status:429,headers:{"retry-after":"1"}}):call===2?new Response("",{status:529}):new Response(JSON.stringify({candidates:[{finishReason:"STOP",content:{parts:[{text:'{"ok":true}'}]}}]})));await expect(client.generateWithRetry("gemini","key",request,new Set(["allowed"]),{maxRetries:2,baseMs:10},async ms=>{waits.push(ms)})).resolves.toMatchObject({value:{ok:true}});expect(waits).toEqual([1000,20]);const invalid=new ProviderClient(async()=>new Response("",{status:401}));await expect(invalid.generateWithRetry("gemini","key",request,new Set(["allowed"]),{maxRetries:3,baseMs:1},async()=>{})).rejects.toMatchObject({code:"invalid_key"})});
});
