import {InstallationClaim} from "../../installation-claim";
import {PermissionReceipt,SetupAccessSummary,SetupHealthState} from "../../live-connections";
import {ModelKeyForm} from "../../model-key-form";
import {notFound} from "next/navigation";

const steps=[
 {id:"install",label:"GitHub",title:"Choose repository access",description:"GitHub—not BuildIT—shows the permission request and lets you select specific repositories."},
 {id:"repository",label:"Repository",title:"Confirm repository policy",description:"Review trusted checks, protected paths, Autofix delivery, budget, and retention before any execution."},
 {id:"model",label:"Model",title:"Connect AI only when needed",description:"A model key is optional until you start AI analysis or Autofix. Deterministic checks can be configured first."},
 {id:"health",label:"Verify",title:"Prove the setup boundary",description:"BuildIT verifies access, configuration, runner isolation, and provider readiness without running repository code."},
];
export async function generateMetadata({params}:{params:Promise<{step:string}>}){
 const{step}=await params;
 // Same reason as [section]: after the shell streams, the status is already sent.
 const found=steps.find(item=>item.id===step);
 if(!found)notFound();
 return{title:`${found.title} · BuildIT`};
}

export default async function Setup({params,searchParams}:{params:Promise<{step:string}>;searchParams:Promise<{installation_id?:string}>}){const{step}=await params,query=await searchParams,index=steps.findIndex(item=>item.id===step);if(index<0)notFound();const current=steps[index]!,installationId=query.installation_id&&/^\d+$/.test(query.installation_id)?Number(query.installation_id):null;return <div className="content setup-page"><a className="back-link" href="/">← Leave setup and keep exploring</a><ol className="stepper">{steps.map((item,position)=><li key={item.id} data-current={position===index||undefined} data-complete={position<index||undefined}><span>{position+1}</span><small>{item.label}</small></li>)}</ol><div className="setup-layout"><div className="setup-main"><p className="eyebrow">Step {index+1} of {steps.length} · resumable</p><h1 className="title">{current.title}</h1><p className="page-description">{current.description}</p>{step==="install"?<><InstallStep/>{installationId?<InstallationClaim installationId={installationId}/>:null}</>:step==="model"?<ModelKeyForm/>:step==="repository"?<RepositoryStep/>:<SetupHealthState/>}{step!=="install"?<PermissionReceipt/>:null}<footer className="setup-footer"><a className="button secondary" href={index?`/setup/${steps[index-1]!.id}`:"/"}>{index?"Back":"Explore product"}</a><a className="button" href={index<steps.length-1?`/setup/${steps[index+1]!.id}`:"/reviews"}>{index<steps.length-1?"Continue":"Open review queue"}</a></footer></div><aside><SetupAccessSummary stepIndex={index}/></aside></div></div>}
function InstallStep(){return <section className="setup-card"><div className="trust-intro"><p className="eyebrow">Why connect GitHub?</p><h2>To inspect one exact pull request and return evidence where your team already works</h2><p>Sign-in proves who you are; it does not expose code. This separate GitHub App step lets you choose the exact public or private repositories BuildIT may access. Unselected repositories remain invisible.</p></div><h2>Exact maximum permissions</h2><div className="permission-list"><div><code>Metadata · read</code><span>Identify selected repositories and resolve who may trigger a review.</span></div><div><code>Contents · write maximum</code><span>Review tokens are read-only. A short-lived write token is created only after Autofix consent, and only to deliver a stacked PR.</span></div><div><code>Pull requests · write</code><span>Read PR context, update one BuildIT summary, and open a stacked PR.</span></div><div><code>Issues · read</code><span>Read linked GitHub Issue intent so findings match the requested behavior.</span></div><div><code>Checks · write</code><span>Publish the BuildIT result against the exact reviewed commit.</span></div></div><div className="trust-terms"><div><strong>Can change</strong><span>One BuildIT check, one PR summary, and—only after consent—a stacked fix branch.</span></div><div><strong>Cannot change</strong><span>BuildIT cannot merge, edit workflows, administer the repository, or see unselected repositories.</span></div><div><strong>Retention</strong><span>Source artifacts are encrypted, expire under the repository policy, and are deleted within 7 days at the latest.</span></div><div><strong>Revoke</strong><span>Remove repositories or uninstall BuildIT in GitHub settings; new access stops immediately and the UI shows recovery steps.</span></div></div><div className="boundary-note"><strong>Never requested:</strong> Administration, Workflows, or merge authority.</div><a className="button" href="https://github.com/apps/buildit-agentic-review/installations/new">Review access in GitHub</a></section>}
function RepositoryStep(){return <section className="setup-card"><h2>Policy preview</h2><div className="policy-preview"><div><span>Validation</span><strong>Tests · typecheck · lint</strong></div><div><span>Autofix</span><strong>Stacked PR · 3 rounds maximum</strong></div><div><span>Protected</span><strong>.github/workflows · migrations</strong></div><div><span>Retention</span><strong>24 hours</strong></div></div><p className="muted-copy">A real repository will load these values from its approved trusted ref. PR-controlled policy is never used for the same review.</p></section>}
