import {InstallationClaim} from "../../installation-claim";
import {SetupAccessSummary,SetupHealthState} from "../../live-connections";

const steps=[
 {id:"install",label:"GitHub",title:"Choose repository access",description:"GitHub—not BuildIT—shows the permission request and lets you select specific repositories."},
 {id:"repository",label:"Repository",title:"Confirm repository policy",description:"Review trusted checks, protected paths, Autofix delivery, budget, and retention before any execution."},
 {id:"model",label:"Model",title:"Connect AI only when needed",description:"A model key is optional until you start AI analysis or Autofix. Deterministic checks can be configured first."},
 {id:"health",label:"Verify",title:"Prove the setup boundary",description:"BuildIT verifies access, configuration, runner isolation, and provider readiness without running repository code."},
];
export default async function Setup({params,searchParams}:{params:Promise<{step:string}>;searchParams:Promise<{installation_id?:string}>}){const{step}=await params,query=await searchParams,index=Math.max(0,steps.findIndex(item=>item.id===step)),current=steps[index]!,installationId=query.installation_id&&/^\d+$/.test(query.installation_id)?Number(query.installation_id):null;return <div className="content setup-page"><a className="back-link" href="/">← Leave setup and keep exploring</a><ol className="stepper">{steps.map((item,position)=><li key={item.id} data-current={position===index||undefined} data-complete={position<index||undefined}><span>{position+1}</span><small>{item.label}</small></li>)}</ol><div className="setup-layout"><main><p className="eyebrow">Step {index+1} of {steps.length} · resumable</p><h1 className="title">{current.title}</h1><p className="page-description">{current.description}</p>{step==="install"?<><InstallStep/>{installationId?<InstallationClaim installationId={installationId}/>:null}</>:step==="model"?<ModelStep/>:step==="repository"?<RepositoryStep/>:<SetupHealthState/>}<footer className="setup-footer"><a className="button secondary" href={index?`/setup/${steps[index-1]!.id}`:"/"}>{index?"Back":"Explore product"}</a><a className="button" href={index<steps.length-1?`/setup/${steps[index+1]!.id}`:"/reviews"}>{index<steps.length-1?"Continue":"Open review queue"}</a></footer></main><aside><SetupAccessSummary stepIndex={index}/></aside></div></div>}
function InstallStep(){return <section className="setup-card"><h2>Exact maximum permissions</h2><div className="permission-list"><div><code>Metadata · read</code><span>Identify selected repositories and resolve trigger authority.</span></div><div><code>Contents · write maximum</code><span>Review tokens are read-only. A fresh write token exists only for validated stacked-PR delivery.</span></div><div><code>Pull requests · write</code><span>Read PR context, update one summary, and open a stacked PR.</span></div><div><code>Issues · read</code><span>Read linked GitHub Issue intent.</span></div><div><code>Checks · write</code><span>Publish the BuildIT Check at the pinned commit.</span></div></div><div className="boundary-note"><strong>Never requested:</strong> Administration, Workflows, or merge authority.</div><a className="button" href="https://github.com/apps/buildit-agentic-review/installations/new">Choose repositories in GitHub</a></section>}
function ModelStep(){return <section className="setup-card"><div className="optional-heading"><div><h2>Bring your own model key</h2><p>You can skip this and continue exploring. The key becomes necessary only when AI analysis starts.</p></div><span className="status neutral">Optional now</span></div><label className="field"><span>Provider</span><select defaultValue="anthropic"><option value="anthropic">Anthropic</option><option value="openai">OpenAI</option><option value="gemini">Google Gemini</option></select></label><label className="field"><span>API key</span><input type="password" placeholder="Stored only after encryption is production-ready" disabled/></label><div className="boundary-note">Credential storage remains disabled in this preview. The UI will not pretend a key was saved.</div></section>}
function RepositoryStep(){return <section className="setup-card"><h2>Policy preview</h2><div className="policy-preview"><div><span>Validation</span><strong>Tests · typecheck · lint</strong></div><div><span>Autofix</span><strong>Stacked PR · 3 rounds maximum</strong></div><div><span>Protected</span><strong>.github/workflows · migrations</strong></div><div><span>Retention</span><strong>24 hours</strong></div></div><p className="muted-copy">A real repository will load these values from its approved trusted ref. PR-controlled policy is never used for the same review.</p></section>}
