"use client";
import { useQuery } from "convex/react";
import { makeFunctionReference } from "convex/server";

// Every number BuildIT published about itself was typed into a page by a person. /features and
// /data-handling at least read track-record.json, but that file is regenerated by hand, so it is a
// snapshot of whenever someone last remembered to run the script. A stranger evaluating a product
// whose entire pitch is "do not take our word for it" had to take our word for it.
//
// This page is the live answer: a public, unauthenticated Convex query against the same production
// database the product runs on, rendering counts only. It shows the platform failures next to the
// completed reviews, because a proof page that reports only the flattering half is marketing.

export type ProofSummary = {
  generatedAt: number;
  rowCeiling: number;
  reviews: { counted: number; truncated: boolean; byStatus: Record<string, number>; repositoriesReviewed: number };
  findings: { counted: number; truncated: boolean };
  spend: { modelSpendUsd: number; modelTokens: number; counted: number; truncated: boolean };
  durationMs: { sampleSize: number; median: number | null; p95: number | null };
};

const proofQuery = makeFunctionReference<"query", Record<string, never>, ProofSummary>("publicProof:summary");

// The stored status is BuildIT's own enum from convex/validators.ts. An unmapped one falls back to
// the raw value rather than being dropped, so a status added on the server appears here as itself
// instead of silently vanishing from a page whose whole claim is completeness.
const statusLabels: Record<string, string> = {
  queued: "Queued", gathering_context: "Gathering context", analyzing: "Analyzing",
  validating: "Validating", checks_passed: "Checks passed", changes_requested: "Changes requested",
  inconclusive: "Inconclusive", autofix_queued: "Autofix queued", autofixing: "Autofixing",
  validating_round: "Validating round", validating_final: "Validating final", delivered: "Autofix delivered",
  failed_after_bounds: "Failed after bounds", blocked: "Blocked", cancelling: "Cancelling",
  cancelled: "Cancelled", budget_exhausted: "Budget exhausted", platform_failed: "Platform failure",
};
const statusTones: Record<string, string> = {
  checks_passed: "success", delivered: "success",
  changes_requested: "warning", inconclusive: "warning", blocked: "warning",
  platform_failed: "danger", failed_after_bounds: "danger", budget_exhausted: "danger",
  queued: "info", gathering_context: "info", analyzing: "info", validating: "info",
  autofix_queued: "info", autofixing: "info", validating_round: "info", validating_final: "info",
};
// A verdict a human can act on. Everything else is either still running or an admission of failure.
const decisiveStatuses = ["checks_passed", "changes_requested", "delivered"];

function duration(ms: number | null) {
  if (ms === null) return "—";
  if (ms < 1000) return `${ms} ms`;
  const seconds = ms / 1000;
  if (seconds < 90) return `${seconds.toFixed(1)}s`;
  return `${Math.floor(seconds / 60)}m ${String(Math.round(seconds % 60)).padStart(2, "0")}s`;
}

function money(usd: number) {
  if (usd === 0) return "$0.00";
  if (usd < 0.01) return "<$0.01";
  return `$${usd.toFixed(2)}`;
}

function readAt(timestamp: number) {
  return `${new Date(timestamp).toISOString().slice(0, 19).replace("T", " ")} UTC`;
}

function Metric({ title, value, detail, hero = false }: { title: string; value: string; detail: string; hero?: boolean }) {
  return <article className={`metric${hero ? " hero-metric" : ""}`}><span>{title}</span><strong>{value}</strong><small>{detail}</small></article>;
}

export default function Proof() {
  const data = useQuery(proofQuery, {});

  return <div className="content trust-page">
    <p className="eyebrow">Live production data · no account, no key</p>
    <h1 className="title">BuildIT&rsquo;s own operating numbers</h1>
    <p className="lede">
      Read live from the database BuildIT runs on, by a public query that returns counts and nothing else.
      No repository, organization, person or finding is identifiable from anything on this page. The failures
      are here beside the successes, because a number you can only see when it flatters us is not evidence.
    </p>
    {data === undefined ? <Loading /> : data.reviews.counted === 0 ? <Empty /> : <Numbers data={data} />}
  </div>;
}

function Loading() {
  return <section className="live-state" aria-live="polite">
    <span className="state-pulse" />
    <div><strong>Reading production…</strong><p>Subscribing to the aggregate query. Nothing is cached or pre-rendered.</p></div>
  </section>;
}

function Empty() {
  return <section className="empty-state">
    <span className="empty-mark" aria-hidden="true">0</span>
    <h2>No reviews recorded in this deployment</h2>
    <p>
      The query reached the database and found no reviews. This page reports zero rather than falling back to
      an example, because an illustrative number on a proof page is the defect it exists to prevent.
    </p>
  </section>;
}

function Numbers({ data }: { data: ProofSummary }) {
  const counts = data.reviews.byStatus;
  const total = (names: string[]) => names.reduce((sum, name) => sum + (counts[name] ?? 0), 0);
  const decisive = total(decisiveStatuses);
  const platformFailed = counts.platform_failed ?? 0;
  const abandoned = total(["failed_after_bounds", "budget_exhausted"]);
  const ordered = Object.entries(counts).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
  const bounded = data.reviews.truncated || data.findings.truncated || data.spend.truncated;

  return <>
    <div className="metric-line">
      <Metric hero title="Pull requests reviewed" value={data.reviews.counted.toLocaleString()}
        detail={data.reviews.truncated ? `Most recent ${data.rowCeiling.toLocaleString()}` : "Every review ever recorded"} />
      <Metric title="Repositories" value={data.reviews.repositoriesReviewed.toLocaleString()}
        detail="Distinct repositories, never named" />
      <Metric title="Findings raised" value={data.findings.counted.toLocaleString()}
        detail="Cited to a file, line and commit" />
      <Metric title="Model spend" value={money(data.spend.modelSpendUsd)}
        detail={`${data.spend.modelTokens.toLocaleString()} tokens, billed to each customer's own key`} />
    </div>

    <div className="metric-line">
      <Metric title="Decisive verdicts" value={decisive.toLocaleString()}
        detail="Checks passed, changes requested or Autofix delivered" />
      <Metric title="Platform failures" value={platformFailed.toLocaleString()}
        detail="BuildIT's own fault. Never reported as a pass" />
      <Metric title="Median review" value={duration(data.durationMs.median)}
        detail={`Start to finish, over the last ${data.durationMs.sampleSize.toLocaleString()} reviews that ran to a verdict`} />
      <Metric title="95th percentile" value={duration(data.durationMs.p95)}
        detail="The slow tail, not the average" />
    </div>

    <section className="metric-explainer">
      <div>
        <p className="eyebrow">How to read this</p>
        <h2>{decisive.toLocaleString()} of {data.reviews.counted.toLocaleString()} reviews reached a verdict</h2>
        <p>
          The rest either failed, were cancelled, or are still running. {platformFailed.toLocaleString()} failed
          because BuildIT broke; {abandoned.toLocaleString()} stopped inside their own round, attempt or budget
          bounds, which is a designed refusal rather than a crash. Neither is ever published as a passing check.
        </p>
      </div>
      <div className="formula"><span>Stopped at bounds</span><strong>{abandoned.toLocaleString()}</strong><small>Refused, not crashed</small></div>
      <div className="formula"><span>Inconclusive</span><strong>{(counts.inconclusive ?? 0).toLocaleString()}</strong><small>No verdict claimed</small></div>
    </section>

    <h2 className="title" id="verdict-mix">Every status, exactly as recorded</h2>
    <p className="lede">The complete distribution. Nothing is grouped away, and no row is hidden for being unflattering.</p>
    <dl className="trust-list" aria-labelledby="verdict-mix">
      {ordered.map(([status, count]) => <div key={status}>
        <dt><span className={`status ${statusTones[status] ?? "neutral"}`}>{statusLabels[status] ?? status}</span></dt>
        <dd>{count.toLocaleString()} {count === 1 ? "review" : "reviews"} · {(count / data.reviews.counted * 100).toFixed(1)}%</dd>
      </div>)}
    </dl>

    <h2 className="title">What this page will not tell you</h2>
    <dl className="trust-list">
      <div>
        <dt>Whose code these are</dt>
        <dd>The query returns a count of distinct repositories, never a repository, owner, organization or branch. Reviews belong to the customers who ran them, and this page is BuildIT&rsquo;s number, not theirs.</dd>
      </div>
      <div>
        <dt>What any finding said</dt>
        <dd>Only how many. Finding text, file paths and line ranges are derived from customer source and never leave an authenticated, tenant-scoped request.</dd>
      </div>
      <div>
        <dt>Accuracy</dt>
        <dd>These are operational counts. Precision and recall are not reported here, and BuildIT does not claim them, because they need blind human adjudication rather than a count of what the model said.</dd>
      </div>
      <div>
        <dt>How far back it reads</dt>
        <dd>
          The query is bounded to the most recent {data.rowCeiling.toLocaleString()} rows of each table, so a live
          subscription can never grow into an unbounded scan of production history.
          {bounded ? " That bound is currently in effect, so these totals are a recent window rather than all time." : " Nothing is currently truncated, so these are complete totals."}
        </dd>
      </div>
    </dl>

    <div className="next">
      <strong>Read at {readAt(data.generatedAt)}.</strong> This page holds an open subscription, so the numbers change
      under you as production moves. Verify it the hard way: the query is <code>convex/publicProof.ts</code>, its
      authorization is declared in <code>convex/publicFunctionPolicy.ts</code>, and both are in the repository.
    </div>
    <div className="button-row">
      <a className="quiet-link" href="/data-handling">What happens to your data</a>
      <a className="quiet-link" href="/sandbox">Run the rules on your own code</a>
    </div>
  </>;
}
