"use client";
import { useAction, useQuery } from "convex/react";
import { makeFunctionReference } from "convex/server";
import { type FormEvent, useState } from "react";
type Repository = { id: string; owner: string; name: string };
type Prepared = { repository: string; credentialScopeId: string; pull: { number: number; title: string; url: string; headSha: string; baseSha: string; changedFiles: number; additions: number; deletions: number; isFork: boolean }; consent: { reads: string[]; runs: string[]; provider: string; model: string; maximumProviderCostUsd: number; writes: string[]; cannot: string[] } };
const prepareAction = makeFunctionReference<"action", { repositoryId: string; prNumber: number }, Prepared>("dashboardReviews:prepare");
const startAction = makeFunctionReference<"action", { repositoryId: string; prNumber: number; expectedHeadSha: string; expectedBaseSha: string; expectedCredentialScopeId: string; consent: true }, { reviewId: string }>("dashboardReviews:start");
const readinessQuery = makeFunctionReference<"query", Record<string, never>, { executionEnabled: boolean }>("runtimeReadiness:current");
export function DashboardReviewStart({ repositories }: { repositories: Repository[] }) {
  const prepare = useAction(prepareAction), start = useAction(startAction), readiness = useQuery(readinessQuery, {}), [repositoryId, setRepositoryId] = useState(repositories[0]?.id ?? ""), [prNumber, setPrNumber] = useState(""), [prepared, setPrepared] = useState<Prepared | null>(null), [working, setWorking] = useState(false), [error, setError] = useState("");
  async function inspect(event: FormEvent) { event.preventDefault(); setWorking(true); setError(""); setPrepared(null); try { setPrepared(await prepare({ repositoryId, prNumber: Number(prNumber) })); } catch (reason) { const message = reason instanceof Error ? reason.message : ""; setError(message.includes("provider_credential_invalid") ? "Add a valid model key before previewing this pull request. BuildIT has not read source, called a model, or run code." : message.includes("github_timeout") ? "GitHub did not respond in time. Nothing started. Check the connection and try the preview again." : "BuildIT could not inspect that pull request with your current repository access. Check the number and selected repository."); } finally { setWorking(false); } }
  async function consent() { if (!prepared || !readiness?.executionEnabled) return; setWorking(true); setError(""); try { const result = await start({ repositoryId, prNumber: prepared.pull.number, expectedHeadSha: prepared.pull.headSha, expectedBaseSha: prepared.pull.baseSha, expectedCredentialScopeId: prepared.credentialScopeId, consent: true }); window.location.assign(`/reviews/${result.reviewId}`); } catch (reason) { const message = reason instanceof Error ? reason.message : "", changed = message.includes("pull_request_changed_review_again"), providerChanged = message.includes("provider_credential_changed_review_again"), safetyBlocked = message.includes("repository_execution_safety_blocked"); setError(safetyBlocked ? "Repository execution is still safety-blocked. No code ran and no provider call or GitHub write occurred." : changed ? "The pull request changed after this preview. Review the new commit before starting." : providerChanged ? "The model-provider key changed after this preview. Inspect the provider and review scope again before starting." : "The review did not start. No code was executed and no GitHub comment was written. Check the model key and repository access, then try again."); setPrepared(null); } finally { setWorking(false); } }
  if (!repositories.length) return null;
  return <section className="review-start" aria-labelledby="start-review-title"><div className="section-heading"><div><p className="eyebrow">First value</p><h2 id="start-review-title">Review a pull request</h2><p>Inspect the exact scope before BuildIT reads source, calls your model provider, or runs code.</p></div></div><form className="review-start-form" onSubmit={inspect}><label className="field"><span>Repository</span><select value={repositoryId} onChange={event => { setRepositoryId(event.target.value); setPrepared(null); }} disabled={working}>{repositories.map(repo => <option key={repo.id} value={repo.id}>{repo.owner}/{repo.name}</option>)}</select></label><label className="field"><span>Pull request number</span><input inputMode="numeric" min="1" step="1" value={prNumber} onChange={event => { setPrNumber(event.target.value.replace(/\D/g, "")); setPrepared(null); }} placeholder="For example, 42" required disabled={working} /></label><button className="button" type="submit" disabled={working || !repositoryId || !prNumber}>{working ? "Checking exact PR…" : "Preview review access"}</button></form>{error ? <p className="form-result error" role="alert">{error}</p> : null}{prepared ? <div className="review-consent"><div className="consent-title"><div><span className="status neutral">Not started</span><h3>{prepared.repository} #{prepared.pull.number} · {prepared.pull.title}</h3><p><code>{prepared.pull.baseSha.slice(0, 7)}</code> → <code>{prepared.pull.headSha.slice(0, 7)}</code> · {prepared.pull.changedFiles} files · +{prepared.pull.additions} −{prepared.pull.deletions}{prepared.pull.isFork ? " · fork review is read-only" : ""}</p></div><a href={prepared.pull.url} target="_blank" rel="noreferrer">Open PR ↗</a></div><div className="consent-grid"><Consent title="BuildIT will read" items={prepared.consent.reads}/><Consent title="BuildIT will run" items={prepared.consent.runs}/><Consent title="BuildIT may write" items={prepared.consent.writes}/><Consent title="BuildIT cannot" items={prepared.consent.cannot}/></div><div className="consent-boundary"><p><strong>AI boundary:</strong> {prepared.consent.model}. Provider spend stops at ${prepared.consent.maximumProviderCostUsd.toFixed(2)} for this review. Missing checks, partial context, stale commits, and unsupported claims are inconclusive—not “safe.”</p><button className="button" type="button" onClick={() => void consent()} disabled={working || !readiness?.executionEnabled}>{working ? "Re-checking commit…" : readiness?.executionEnabled ? "Consent and start review" : "Review execution safety-blocked"}</button></div></div> : null}</section>;
}
function Consent({ title, items }: { title: string; items: string[] }) { return <div><strong>{title}</strong><ul>{items.map(item => <li key={item}>{item}</li>)}</ul></div>; }
