"use client";
import {useConvexAuth,useQuery} from "convex/react";
import {makeFunctionReference} from "convex/server";
import {sampleReviews} from "../sample-data";
import {useSampleTour} from "../workspace-route-boundary";
import {DashboardReviewStart} from "./dashboard-review-start";
type Connection={organization:null|{id:string;name:string};repositories:Array<{id:string;owner:string;name:string}>};
type LiveReview={id:string;repositoryId:string;prNumber:number;headSha:string;status:string;isStale:boolean;coverageLevel:string;currentStage:string;nextActionCode:string;updatedAt:number};
const connectionQuery=makeFunctionReference<"query",Record<string,never>,Connection>("repositoryConnections:current"),reviewsQuery=makeFunctionReference<"query",{organizationId:string},LiveReview[]>("reviews:list"),active=new Set(["queued","gathering_context","analyzing","validating","autofix_queued","autofixing","validating_round","validating_final"]),label=(value:string)=>value.replaceAll("_"," ").replace(/^./,first=>first.toUpperCase()),tone=(status:string)=>status==="checks_passed"||status==="delivered"?"success":["blocked","changes_requested","failed_after_bounds","platform_failed"].includes(status)?"danger":active.has(status)?"running":"neutral";
export default function ReviewQueue(){const tour=useSampleTour(),{isAuthenticated}=useConvexAuth(),connection=useQuery(connectionQuery,!tour&&isAuthenticated?{}:"skip"),reviews=useQuery(reviewsQuery,!tour&&connection?.organization?{organizationId:connection.organization.id}:"skip");if(tour)return <SampleQueue/>;if(!connection||reviews===undefined)return <div className="content"><Heading connected/><section className="live-state" aria-live="polite"><span className="state-pulse"/><div><strong>Loading your review queue…</strong><p>Checking the active organization on the server.</p></div></section></div>;const rows=[...reviews].sort((a,b)=>b.updatedAt-a.updatedAt),running=rows.filter(item=>active.has(item.status)),decisions=rows.filter(item=>!active.has(item.status));return <div className="content"><Heading connected/><DashboardReviewStart repositories={connection.repositories}/><LiveGroup title="Needs decision" reviews={decisions} connection={connection}/><LiveGroup title="Running" reviews={running} connection={connection}/>{rows.length===0?<section className="empty-state live-empty"><span className="empty-mark">PR</span><h2>No reviews in {connection.organization?.name}</h2><p>Preview a pull request above, or comment <code>@buildit review</code> on GitHub. Both paths pin the exact commits before a review starts.</p><div className="button-row"><a className="button secondary" href="/repositories">Open repositories</a><a className="button tertiary" href="/setup/model">Check model key</a></div></section>:null}</div>}
function Heading({connected=false}:{connected?:boolean}){return <div className="page-heading"><div><p className="eyebrow">{connected?"Live workspace · active organization":"Sample evidence · no repository connected"}</p><h1 className="title">Review queue</h1><p className="page-description">Prioritized by the next human action—not by when a webhook arrived.</p></div><div className="heading-actions"><a className="button" href={connected?"/repositories":"/setup/install"}>{connected?"View repositories":"Connect repository"}</a></div></div>}
function LiveGroup({title,reviews,connection}:{title:string;reviews:LiveReview[];connection:Connection}){if(!reviews.length)return null;return <section className="review-group"><div className="section-heading compact"><h2>{title}</h2><span className="count">{reviews.length}</span></div><div className="review-table" role="table" aria-label={title}>{reviews.map(review=>{const repository=connection.repositories.find(item=>item.id===review.repositoryId);return <a role="row" className="review-row" href={`/reviews/${review.id}`} key={review.id}><span role="cell" className={`status ${tone(review.status)}`}>{label(review.status)}</span><span role="cell" className="review-name"><strong>{repository?`${repository.owner}/${repository.name}`:"Authorized repository"} #{review.prNumber}</strong><small>{review.isStale?"Head changed · start a new review":`Next: ${label(review.nextActionCode)}`}</small></span><code role="cell">{review.headSha.slice(0,7)}</code><span role="cell">{label(review.coverageLevel)}</span><span role="cell" className="signal">{label(review.currentStage)}</span><time role="cell">{new Date(review.updatedAt).toLocaleString()}</time></a>})}</div></section>}
function SampleQueue(){const needsDecision=sampleReviews.filter(review=>review.status!=="Running"),running=sampleReviews.filter(review=>review.status==="Running");return <div className="content"><Heading/><SampleGroup title="Needs decision" reviews={needsDecision}/><SampleGroup title="Running" reviews={running}/><section className="empty-band"><div><strong>This is an interactive product tour</strong><p>Connect GitHub to replace these clearly marked examples with tenant-scoped review records.</p></div><a href="/data-handling">Read retention policy →</a></section></div>}
function SampleGroup({title,reviews}:{title:string;reviews:typeof sampleReviews}){return <section className="review-group"><div className="section-heading compact"><h2>{title}</h2><span className="count">{reviews.length}</span></div><div className="review-table" role="table" aria-label={title}>{reviews.map(review=><a role="row" className="review-row" href={`/reviews/${review.pr}?tour=1`} key={review.pr}><span role="cell" className={`status ${review.tone}`}>{review.status}</span><span role="cell" className="review-name"><strong>{review.repo} #{review.pr}</strong><small>{review.title}</small></span><code role="cell">{review.commit}</code><span role="cell">{review.coverage}</span><span role="cell" className="signal">{review.signal}</span><span role="cell">{review.owner}</span><time role="cell">{review.age}</time></a>)}</div></section>}
