import { describe, expect, it } from "vitest";
import { assertAutofixBounds, conservativeModelCost, contentHash, validatePatchProposals } from "../src/patchPolicy";

const source = "export const tax = 1;\n", hash = contentHash(source), accepted = new Set(["finding-1"]);
const proposal = { path: "src/tax.ts", rationale: "Fix supported tax finding", findingIds: ["finding-1"], expectedContentHash: hash, replacementContent: "export const tax = 2;\n" };

describe("Autofix patch policy", () => {
  it("accepts an exact-source replacement tied to an accepted finding", () => expect(validatePatchProposals({ proposals: [proposal], sources: [{ path: proposal.path, content: source, contentHash: hash }], acceptedFindingIds: accepted })).toEqual([{ ...proposal, previousContent: source }]));
  it("rejects stale content, unsupported findings, duplicate and protected paths", () => {
    expect(() => validatePatchProposals({ proposals: [{ ...proposal, expectedContentHash: "a".repeat(64) }], sources: [{ path: proposal.path, content: source, contentHash: hash }], acceptedFindingIds: accepted })).toThrow("patch_source_mismatch");
    expect(() => validatePatchProposals({ proposals: [{ ...proposal, findingIds: ["invented"] }], sources: [{ path: proposal.path, content: source, contentHash: hash }], acceptedFindingIds: accepted })).toThrow("patch_finding_scope_invalid");
    expect(() => validatePatchProposals({ proposals: [proposal, proposal], sources: [{ path: proposal.path, content: source, contentHash: hash }], acceptedFindingIds: accepted })).toThrow("patch_path_duplicate");
    expect(() => validatePatchProposals({ proposals: [{ ...proposal, path: ".github/workflows/release.yml" }], sources: [{ path: ".github/workflows/release.yml", content: source, contentHash: hash }], acceptedFindingIds: accepted })).toThrow("patch_path_protected");
  });
  it("rejects empty, oversized, and likely-secret replacements", () => {
    expect(() => validatePatchProposals({ proposals: [{ ...proposal, replacementContent: source }], sources: [{ path: proposal.path, content: source, contentHash: hash }], acceptedFindingIds: accepted })).toThrow("patch_empty");
    expect(() => validatePatchProposals({ proposals: [{ ...proposal, replacementContent: "x".repeat(10) }], sources: [{ path: proposal.path, content: source, contentHash: hash }], acceptedFindingIds: accepted, maxBytes: 5 })).toThrow("patch_byte_limit_exceeded");
    expect(() => validatePatchProposals({ proposals: [{ ...proposal, replacementContent: 'api_key = "abcdefghijklmnop1234"' }], sources: [{ path: proposal.path, content: source, contentHash: hash }], acceptedFindingIds: accepted })).toThrow("patch_potential_secret");
  });
  it.each([".github/workflows/test.yml","CODEOWNERS","Dockerfile","vercel.json","package.json","pnpm-lock.yaml","pyproject.toml","requirements.txt","pom.xml","infra/main.tf","db/migrations/1.sql",".env.production"])("protects delivery, ownership, dependency, migration, and secret path %s",path=>{expect(()=>validatePatchProposals({proposals:[{...proposal,path}],sources:[{path,content:source,contentHash:hash}],acceptedFindingIds:accepted})).toThrow("patch_path_protected")});
  it.each(["../src/tax.ts","/src/tax.ts","src/../../tax.ts","src/\0tax.ts"])("rejects unsafe path %s",path=>{expect(()=>validatePatchProposals({proposals:[{...proposal,path}],sources:[{path,content:source,contentHash:hash}],acceptedFindingIds:accepted})).toThrow("patch_path_protected")});
  it("rejects NUL content and enforces the file ceiling",()=>{expect(()=>validatePatchProposals({proposals:[{...proposal,replacementContent:"bad\0content"}],sources:[{path:proposal.path,content:source,contentHash:hash}],acceptedFindingIds:accepted})).toThrow("patch_content_invalid");expect(()=>validatePatchProposals({proposals:[proposal,{...proposal,path:"src/other.ts"}],sources:[{path:proposal.path,content:source,contentHash:hash},{path:"src/other.ts",content:source,contentHash:hash}],acceptedFindingIds:accepted,maxFiles:1})).toThrow("patch_file_limit_exceeded")});
});
describe("Autofix termination bounds",()=>{it("returns only the next bounded round",()=>expect(assertAutofixBounds({completedRounds:1,modelAttempts:3,startedAt:1_000,now:2_000,budgetConsumed:1,budgetLimit:5})).toMatchObject({roundNumber:2,remainingAttempts:3}));it.each([[3,0,"autofix_round_limit"],[0,6,"autofix_attempt_limit"]])("rejects rounds %s and attempts %s",(completedRounds,modelAttempts,error)=>expect(()=>assertAutofixBounds({completedRounds,modelAttempts,startedAt:1_000,now:2_000,budgetConsumed:1,budgetLimit:5})).toThrow(error));it("rejects expired time and exhausted spend",()=>{expect(()=>assertAutofixBounds({completedRounds:0,modelAttempts:0,startedAt:1,now:45*60_000+2,budgetConsumed:0,budgetLimit:5})).toThrow("autofix_time_limit");expect(()=>assertAutofixBounds({completedRounds:0,modelAttempts:0,startedAt:1,now:2,budgetConsumed:5,budgetLimit:5})).toThrow("autofix_spend_limit")});it("prices usage with a conservative provider ceiling",()=>expect(conservativeModelCost(1_000_000,1_000_000)).toBe(90))});
