import {createHmac,timingSafeEqual} from "node:crypto";
export function verifyWebhook(body:Buffer,signature:string|undefined,secret:string){if(!signature?.startsWith("sha256="))return false;const expected=Buffer.from(createHmac("sha256",secret).update(body).digest("hex"),"hex");let actual:Buffer;try{actual=Buffer.from(signature.slice(7),"hex")}catch{return false}return actual.length===expected.length&&timingSafeEqual(actual,expected)}
export type TriggerInput={deliveryId:string;action:string;senderType:string;body:string;permission:"read"|"triage"|"write"|"maintain"|"admin"};
const command=/^\s*@buildit\s+(review|autofix|cancel)(?:\s+(stacked))?\s*$/im;
export function authorizeTrigger(input:TriggerInput){if(input.senderType==="Bot")return{accepted:false as const,reason:"bot"};if(input.action==="edited")return{accepted:false as const,reason:"edited"};const match=input.body.match(command);if(!match)return{accepted:false as const,reason:"no_command"};const kind=match[1]!;const allowed=kind==="review"?["triage","write","maintain","admin"]:["write","maintain","admin"];return allowed.includes(input.permission)?{accepted:true as const,kind,mode:match[2]??"default"}:{accepted:false as const,reason:"permission"}}
export class DeliveryLedger{#ids=new Set<string>();accept(id:string){if(this.#ids.has(id))return false;this.#ids.add(id);return true}}
export function trustedConfiguration(input:{defaultBranch:string;trustedRef?:string;headSha:string;trustedSha:string;protectionVerified:boolean;explicitlyApproved:boolean}){const ref=input.trustedRef??input.defaultBranch;if(input.headSha===input.trustedSha)throw new Error("configuration_must_not_come_from_pr_head");return{ref,sha:input.trustedSha,provenance:input.protectionVerified?"protected_ref_merge":input.explicitlyApproved?"explicit_admin_approval":"defaults_only" as const}}
export function canCommitSensitiveWrite(pinned:string,current:string){return pinned===current}
export type StackedPrClient={createBranch(input:{name:string;sha:string}):Promise<void>;createPullRequest(input:{head:string;base:string;title:string;body:string}):Promise<{number:number;url:string}>};
export async function deliverStackedPr(client:StackedPrClient,input:{jobId:string;prNumber:number;sourceBranch:string;pinnedHead:string;currentHead:string;candidateSha:string;allRequiredChecksPassed:boolean;existing?:{number:number;url:string}}){if(input.existing)return input.existing;if(!canCommitSensitiveWrite(input.pinnedHead,input.currentHead))throw new Error("stale_head");if(!input.allRequiredChecksPassed)throw new Error("final_validation_required");const branch=`buildit/pr-${input.prNumber}/${input.jobId}`;await client.createBranch({name:branch,sha:input.candidateSha});return client.createPullRequest({head:branch,base:input.sourceBranch,title:`BuildIT fixes for PR #${input.prNumber}`,body:`Validated candidate ${input.candidateSha}. Human approval and merge required.`})}
