import { githubRequester } from "./request.js";
type Http=(input:string|URL,init?:RequestInit)=>Promise<Response>;
export type TrackerContext={status:"available"|"missing"|"inaccessible"|"image_only"|"oversized";version:string;content?:string};
function bounded(content:string,version:string,maxBytes:number,imageOnly=false):TrackerContext{if(imageOnly)return{status:"image_only",version};if(Buffer.byteLength(content)>maxBytes)return{status:"oversized",version};return{status:"available",version,content}}
function textFromAdf(value:unknown):{text:string;media:boolean}{if(!value||typeof value!=="object")return{text:"",media:false};const node=value as Record<string,unknown>,own=typeof node.text==="string"?node.text:"",children=Array.isArray(node.content)?node.content.map(textFromAdf):[],media=node.type==="media"||node.type==="mediaSingle"||children.some(item=>item.media);return{text:[own,...children.map(item=>item.text)].filter(Boolean).join(node.type==="paragraph"?"":"\n"),media}}
export class LinearContextClient{private readonly http:Http;constructor(http:Http=fetch){this.http=githubRequester(http)}async fetch(input:{token:string;url:string;workspaceSlug:string;maxBytes?:number;oauth?:boolean;projectKeys?:string[]}):Promise<TrackerContext>{const maxBytes=input.maxBytes??250_000,match=input.url.match(/^https:\/\/linear\.app\/([^/]+)\/issue\/([A-Z][A-Z0-9_]*-\d+)(?:\/[^?#]*)?$/i);if(!match||match[1]!.toLowerCase()!==input.workspaceSlug.toLowerCase()||maxBytes<1||maxBytes>1_000_000)throw new Error("linear_scope_mismatch");if(input.projectKeys&&!input.projectKeys.includes(match[2]!.replace(/-\d+$/, "").toUpperCase()))throw new Error("linear_scope_mismatch");const response=await this.http("https://api.linear.app/graphql",{method:"POST",headers:{authorization:input.oauth?`Bearer ${input.token}`:input.token,"content-type":"application/json"},body:JSON.stringify({query:"query BuildITIssue($id:String!){ issue(id:$id){ identifier title description updatedAt url } }",variables:{id:match[2]}})});if(response.status===401||response.status===403)return{status:"inaccessible",version:"inaccessible"};if(!response.ok)throw new Error(`linear_issue_${response.status}`);const body=await response.json() as {data?:{issue?:{identifier?:unknown;title?:unknown;description?:unknown;updatedAt?:unknown;url?:unknown}};errors?:unknown[]},issue=body.data?.issue;if(!issue){if(body.errors?.length)throw new Error("linear_issue_malformed");return{status:"missing",version:"missing"}}if(typeof issue.identifier!=="string"||issue.identifier.toUpperCase()!==match[2]!.toUpperCase()||typeof issue.updatedAt!=="string"||typeof issue.url!=="string"||!issue.url.startsWith(`https://linear.app/${input.workspaceSlug}/`))throw new Error("linear_issue_malformed");const title=typeof issue.title==="string"?issue.title:"",description=typeof issue.description==="string"?issue.description:"",withoutImages=description.replace(/!\[[^\]]*\]\([^)]*\)/g,"").trim();return bounded(`# ${title}\n${description}`,issue.updatedAt,maxBytes,!withoutImages&&/!\[[^\]]*\]\([^)]*\)/.test(description))}}
export class JiraContextClient{private readonly http:Http;constructor(http:Http=fetch){this.http=githubRequester(http)}async fetch(input:{token:string;url:string;siteHost:string;maxBytes?:number;cloudId?:string;projectKeys?:string[]}):Promise<TrackerContext>{const maxBytes=input.maxBytes??250_000,expected=input.siteHost.toLowerCase(),match=input.url.match(/^https:\/\/([^/]+)\/browse\/([A-Z][A-Z0-9_]*-\d+)$/i);if(!match||match[1]!.toLowerCase()!==expected||!expected.endsWith(".atlassian.net")||maxBytes<1||maxBytes>1_000_000)throw new Error("jira_scope_mismatch");if((input.projectKeys&&!input.projectKeys.includes(match[2]!.replace(/-\d+$/, "").toUpperCase()))||(input.cloudId&&!/^[a-z0-9_-]{1,200}$/i.test(input.cloudId)))throw new Error("jira_scope_mismatch");const apiOrigin=input.cloudId?`https://api.atlassian.com/ex/jira/${encodeURIComponent(input.cloudId)}`:`https://${expected}`;const response=await this.http(`${apiOrigin}/rest/api/3/issue/${encodeURIComponent(match[2]!)}?fields=summary,description,updated`,{headers:{authorization:`Bearer ${input.token}`,accept:"application/json"}});if(response.status===404)return{status:"missing",version:"missing"};if(response.status===401||response.status===403)return{status:"inaccessible",version:"inaccessible"};if(!response.ok)throw new Error(`jira_issue_${response.status}`);const body=await response.json() as {key?:unknown;fields?:{summary?:unknown;description?:unknown;updated?:unknown}};if(typeof body.key!=="string"||body.key.toUpperCase()!==match[2]!.toUpperCase()||typeof body.fields?.updated!=="string")throw new Error("jira_issue_malformed");const description=textFromAdf(body.fields.description),title=typeof body.fields.summary==="string"?body.fields.summary:"";return bounded(`# ${title}\n${description.text}`,body.fields.updated,maxBytes,description.media)}}


// Select only credentials whose approved workspace and project can serve this linked issue.
export function trackerConnectionMatches(connection: { provider: string; workspaceId: string; projectKeys?: string[] }, link: { type: string; url: string }) {
  if (connection.provider !== link.type) return false;
  const match = link.type === "linear" ? link.url.match(/^https:\/\/linear\.app\/([^/]+)\/issue\/([A-Z][A-Z0-9_]*-\d+)(?:\/[^?#]*)?$/i) : link.url.match(/^https:\/\/([^/]+)\/browse\/([A-Z][A-Z0-9_]*-\d+)$/i);
  return Boolean(match && match[1]!.toLowerCase() === connection.workspaceId.toLowerCase() && (!connection.projectKeys || connection.projectKeys.includes(match[2]!.replace(/-\d+$/, "").toUpperCase())));
}
