import {describe,expect,it} from "vitest";
import {auditDeterministicGrader,correctCandidate,deterministicGrade,evaluationStages,frozenStageCatalog,frozenStageGold,frozenStageInputs,gradeFrozenStage,graderMutations} from "../src/grader.js";
describe("deterministic grader audit",()=>{
  it("freezes 49 opaque model inputs separately from evaluator metadata and gold answers",()=>{expect(frozenStageInputs).toHaveLength(49);expect(frozenStageGold).toHaveLength(49);expect(frozenStageInputs.map(item=>item.id)).toEqual(frozenStageGold.map(item=>item.id));for(const stage of evaluationStages)expect(new Set(frozenStageCatalog.filter(testCase=>testCase.stage===stage).map(testCase=>testCase.kind))).toEqual(new Set(["positive","negative","ambiguous","no_finding","inaccessible_context","malformed_provider","prompt_injection"]));const modelFacing=JSON.stringify(frozenStageInputs);for(const leaked of ["positive","negative","ambiguous","no_finding","inaccessible_context","malformed_provider","prompt_injection","goldDisposition"])expect(modelFacing).not.toContain(`\"kind\":\"${leaked}\"`)});
  it("accepts a gold-conforming stage result",()=>{const input=frozenStageInputs[0]!,gold=frozenStageGold[0]!;expect(gradeFrozenStage({id:input.id,disposition:gold.disposition,facts:gold.requiredFacts,evidenceIds:[input.allowedEvidenceIds[0]!],claims:[]})).toEqual({accepted:true,reasons:[]})});
  it("rejects wrong disposition, missing facts, invented evidence, and unsafe claims together",()=>{const input=frozenStageInputs[0]!,gold=frozenStageGold[0]!;expect(gradeFrozenStage({id:input.id,disposition:gold.disposition==="accept"?"reject":"accept",facts:[],evidenceIds:["invented"],claims:["This is bug-free and secure"]})).toEqual({accepted:false,reasons:["disposition_mismatch","required_fact_missing","citation_invalid","forbidden_claim"]})});
  it("accepts the known-correct control",()=>expect(deterministicGrade(correctCandidate)).toEqual({accepted:true,reasons:[]}));
  it.each(graderMutations)("rejects the deliberately broken $name output",({candidate,expectedReason})=>expect(deterministicGrade(candidate)).toEqual({accepted:false,reasons:[expectedReason]}));
  it("will not report a trustworthy grader unless every mutation is caught",()=>expect(auditDeterministicGrader()).toEqual({passed:true,falseAcceptCount:0,falseRejectCount:0,caseCount:11}));
});
