import { describe, expect, it } from "vitest";
import { releaseGate, score, type EvaluationRun } from "../src/score.js";
const finding = (index: number, repetition: number) => { const expected = index >= 15; return { caseId: `case-${index}`, language: ["typescript", "python", "java"][index % 3]!, risk: index % 10 === 0 ? "critical" as const : "high" as const, expected, surfaced: expected, ...(expected ? { expectedSeverity: index % 10 === 0 ? "critical" as const : "high" as const, predictedSeverity: index % 10 === 0 ? "critical" as const : "high" as const } : {}), evidenceSupported: true, repeatGroup: `case-${index}`, repetition }; };
const passing = (): EvaluationRun => ({ setVersion: "blind-v1", promptVersion: "chain-v1", findings: Array.from({ length: 50 }, (_, index) => [0, 1, 2].map(repetition => finding(index, repetition))).flat(), patches: Array.from({ length: 20 }, (_, index) => ({ caseId: `case-${index + 15}`, language: ["typescript", "python", "java"][index % 3]!, risk: "high", proposed: true, appliedCleanly: true, requiredChecksPassed: true, introducedRegression: false })), latencyMs: [1_000, 2_000], costUsd: [1, 2] });
describe("accuracy release scorecard", () => {
  it("passes only a broad benchmark with negatives and three stable repetitions", () => { const result = releaseGate(passing()); expect(result.passed).toBe(true); expect(result.score).toMatchObject({ caseCount: 50, languageCount: 3, negativeCaseCount: 15, repeatedCaseCoverage: 1, precision: 1, criticalRecall: 1, patchRegressionRate: 0 }); });
  it("fails closed on tiny or missing benchmark evidence", () => { const run = passing(); run.findings = run.findings.slice(0, 2); run.patches = []; run.latencyMs = []; run.costUsd = []; const result = releaseGate(run); expect(result.passed).toBe(false); expect(result.failures).toEqual(expect.arrayContaining(["caseCount_below_threshold", "patchApplyRate_below_threshold", "p95CostUsd_above_threshold"])); });
  it("rejects unsupported claims, unstable output, regressions, and bad severity even when raw recall is high", () => { const run = passing(); for (let index = 45; index < 78; index += 1) run.findings[index] = { ...run.findings[index]!, predictedSeverity: "low" }; for (const index of [45, 48, 51]) run.findings[index] = { ...run.findings[index]!, evidenceSupported: false }; for (const index of [46, 49, 52, 55, 58, 61]) run.findings[index] = { ...run.findings[index]!, surfaced: false }; run.patches[0] = { ...run.patches[0]!, introducedRegression: true, requiredChecksPassed: false }; const result = releaseGate(run); expect(result.passed).toBe(false); expect(result.failures).toEqual(expect.arrayContaining(["unsupportedClaimRate_above_threshold", "severityAccuracy_below_threshold", "stability_below_threshold", "patchRegressionRate_above_threshold"])); });
  it("does not misuse human acceptance or changed LOC as accuracy", () => { const run = passing(); run.patches = run.patches.map(item => ({ ...item, humanAccepted: false })); expect(score(run).precision).toBe(1); expect(releaseGate(run).passed).toBe(true); });
  it("rejects a synthetic one-shot benchmark even when every prediction is correct", () => { const run = passing(); run.findings = run.findings.filter((_, index) => index % 3 === 0); const result = releaseGate(run); expect(result.passed).toBe(false); expect(result.failures).toContain("repeatedCaseCoverage_below_threshold"); });
  it("rejects a benchmark without enough negative cases", () => { const run = passing(); run.findings = run.findings.map(row => ({ ...row, expected: true, surfaced: true, expectedSeverity: row.expectedSeverity ?? "high", predictedSeverity: row.predictedSeverity ?? "high" })); const result = releaseGate(run); expect(result.passed).toBe(false); expect(result.failures).toContain("negativeCaseCount_below_threshold"); });
});
